/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica_05_ssuquilanda_jabad.vista.cliente;

import ec.edu.ups.practica_05_ssuquilanda_jabad.controlador.ControladorCompositor;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Cantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Compositor;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaListarCliente extends javax.swing.JInternalFrame {

    private ControladorCompositor controladorCompositor;
    private ResourceBundle mensajes;

    /**
     * Creates new form VentanaListarCantante
     */
    public VentanaListarCliente(ControladorCompositor controladorCompositor) {
        initComponents();
        this.controladorCompositor  = controladorCompositor;
        
    }
    public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jLabel3.setText(mensajes.getString("txtIngresarCódigoDelCompositorParaListarSusClientes"));
        lblNombreCrearPersona5.setText(mensajes.getString("txtCódigo"));
        lblNombreCrearPersona4.setText(mensajes.getString("txtNombre"));        
        lblFechaNacimientoCrearPersona1.setText(mensajes.getString("txtApellido"));        
        lblNombreCrearPersona6.setText(mensajes.getString("txtEdad"));        
        lblNacionalidadBuscarCantante1.setText(mensajes.getString("txtNacionalidad"));       
        lblNumGirasBuscarCantante1.setText(mensajes.getString("txtNúmeroDeComposiciónes"));        
        lblSalarioBuscarCantante1.setText(mensajes.getString("txtSalario"));
        btnBuscarCompositor.setText(mensajes.getString("txtBuscar"));
        
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCantante1 = new javax.swing.JPanel();
        lblFechaNacimientoCrearPersona1 = new javax.swing.JLabel();
        lblNumGirasBuscarCantante1 = new javax.swing.JLabel();
        txtCodigoCompositor = new javax.swing.JTextField();
        txtNombreCompositor = new javax.swing.JTextField();
        lblCantante2 = new javax.swing.JLabel();
        lblNombreCrearPersona4 = new javax.swing.JLabel();
        lblNombreCrearPersona5 = new javax.swing.JLabel();
        lblNombreCrearPersona6 = new javax.swing.JLabel();
        lblNacionalidadBuscarCantante1 = new javax.swing.JLabel();
        txtApellidoCompositor = new javax.swing.JTextField();
        txtEdadCompositor = new javax.swing.JTextField();
        txtNumComposicionesCompositor = new javax.swing.JTextField();
        lblSalarioBuscarCantante1 = new javax.swing.JLabel();
        txtSalarioCompositor = new javax.swing.JTextField();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarCompositor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarCliente = new javax.swing.JTable();
        cbxPaisesCompositor = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 90, -1, -1));

        panelCantante1.setBackground(new java.awt.Color(255, 255, 255));
        panelCantante1.setToolTipText("Crear Nueva Persona");
        panelCantante1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaNacimientoCrearPersona1.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblFechaNacimientoCrearPersona1.setText("Apellido:");
        panelCantante1.add(lblFechaNacimientoCrearPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 30));

        lblNumGirasBuscarCantante1.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumGirasBuscarCantante1.setText("Num. Composiciones:");
        panelCantante1.add(lblNumGirasBuscarCantante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 370, 30));

        txtCodigoCompositor.setToolTipText("Ingrese el codigo del compositor");
        txtCodigoCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(txtCodigoCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 220, 30));

        txtNombreCompositor.setToolTipText("Ingrese el nombre del cantante");
        txtNombreCompositor.setEnabled(false);
        txtNombreCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(txtNombreCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 220, 30));

        lblCantante2.setFont(new java.awt.Font("AkayaTelivigala", 1, 36)); // NOI18N
        lblCantante2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/My project-1-3.png"))); // NOI18N
        lblCantante2.setText("UPS Musik");
        lblCantante2.setPreferredSize(new java.awt.Dimension(200, 400));
        panelCantante1.add(lblCantante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 330, 50));

        lblNombreCrearPersona4.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblNombreCrearPersona4.setText("Nombre:");
        panelCantante1.add(lblNombreCrearPersona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 30));

        lblNombreCrearPersona5.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona5.setText("Codigo:");
        panelCantante1.add(lblNombreCrearPersona5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 30));

        lblNombreCrearPersona6.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona6.setText("Edad:");
        panelCantante1.add(lblNombreCrearPersona6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 78, 30));

        lblNacionalidadBuscarCantante1.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNacionalidadBuscarCantante1.setText("Nacionalidad:");
        panelCantante1.add(lblNacionalidadBuscarCantante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, 30));

        txtApellidoCompositor.setToolTipText("Ingrese el apellido del cantante");
        txtApellidoCompositor.setEnabled(false);
        txtApellidoCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(txtApellidoCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 220, 30));

        txtEdadCompositor.setToolTipText("Ingrese le edad del cantante");
        txtEdadCompositor.setEnabled(false);
        txtEdadCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(txtEdadCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 220, 30));

        txtNumComposicionesCompositor.setToolTipText("Ingrese el genero musical del cantante");
        txtNumComposicionesCompositor.setEnabled(false);
        txtNumComposicionesCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumComposicionesCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(txtNumComposicionesCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 220, 30));

        lblSalarioBuscarCantante1.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblSalarioBuscarCantante1.setText("Salario:");
        panelCantante1.add(lblSalarioBuscarCantante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 120, 30));

        txtSalarioCompositor.setToolTipText("Ingrese el nombre de la nueva persona");
        txtSalarioCompositor.setEnabled(false);
        txtSalarioCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(txtSalarioCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 220, 30));

        jInternalFrame2.setClosable(true);
        jInternalFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setMaximizable(true);
        jInternalFrame2.setResizable(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCantante1.add(jInternalFrame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Hoefler Text", 1, 24)); // NOI18N
        jLabel3.setText("Ingrese el codigo del compositor, del cual se va a listar los clientes:");
        panelCantante1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 920, 40));

        btnBuscarCompositor.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBuscarCompositor.setText("Buscar");
        btnBuscarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(btnBuscarCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 106, 32));

        tblListarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Edad", "Nacionalidad", "Nombre Artistico", "Genero Musical", "Numero Sencillos", "Numero Conciertos", "Numero Giras", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListarCliente);

        panelCantante1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 1350, -1));

        cbxPaisesCompositor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona un País--" }));
        cbxPaisesCompositor.setToolTipText("Puede cambiar la nacionalidad");
        cbxPaisesCompositor.setEnabled(false);
        cbxPaisesCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisesCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(cbxPaisesCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 220, 30));

        getContentPane().add(panelCantante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1890, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        this.cargarDatosTablaCliente();
    }//GEN-LAST:event_formInternalFrameActivated

    private void txtCodigoCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCompositorActionPerformed

    private void txtNombreCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCompositorActionPerformed

    private void txtApellidoCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCompositorActionPerformed

    private void txtEdadCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadCompositorActionPerformed

    private void txtNumComposicionesCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumComposicionesCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumComposicionesCompositorActionPerformed

    private void txtSalarioCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioCompositorActionPerformed

    private void btnBuscarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCompositorActionPerformed
        if (!camposObligatoriosConDatos()) {
            JOptionPane.showMessageDialog(this, "El codigo del compositor a buscar no ha sido ingresado!");
        } else {
            String codigo = txtCodigoCompositor.getText();
            int codiguito = Integer.parseInt(codigo);
            Compositor compositorSeleccionado = controladorCompositor.buscarCompositor(codiguito);
            if (compositorSeleccionado != null) {
                cambiarEstadoCampos(true);
                txtCodigoCompositor.setEnabled(false);
                txtNombreCompositor.setText(compositorSeleccionado.getNombre());
                txtApellidoCompositor.setText(compositorSeleccionado.getApellido());
                String edad = String.valueOf(compositorSeleccionado.getEdad());
                txtEdadCompositor.setText(edad);
                cbxPaisesCompositor.setSelectedItem(compositorSeleccionado.getNacionalidad());
                String numComposiones = String.valueOf(compositorSeleccionado.getNumeroDeComposiciones());
                txtNumComposicionesCompositor.setText(numComposiones);
                String salarioCom = String.valueOf(compositorSeleccionado.getSalario());
                txtSalarioCompositor.setText(salarioCom);
                JOptionPane.showMessageDialog(this, "El/La compositor con codigo " + codiguito + " ha sido encontrado !:(");
                btnBuscarCompositor.setEnabled(true);
                this.cargarDatosTablaCliente();

            } else {
                JOptionPane.showMessageDialog(this, "El/La compositor con codigo " + codiguito + " no ha sido encontrada !:(");

                this.limpiarCamposCompositor();
            }
        }
    }//GEN-LAST:event_btnBuscarCompositorActionPerformed

    private void cbxPaisesCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisesCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPaisesCompositorActionPerformed
    private void cargarDatosTablaCliente() {
        DefaultTableModel modeloCantante = (DefaultTableModel) this.tblListarCliente.getModel();
        modeloCantante.setNumRows(0);
        String codigoCompositor = txtCodigoCompositor.getText();
        int codiguito = Integer.parseInt(codigoCompositor);
        Compositor compositorSeleccionado = controladorCompositor.buscarCompositor(codiguito);
        List<Cantante> listaClientes = controladorCompositor.listarClientes(compositorSeleccionado);
        for (Cantante cantante : listaClientes) {

            String codigo = String.valueOf(cantante.getCodigo());
            String nombre = cantante.getNombre();
            String apellido = cantante.getApellido();
            String edad = String.valueOf(cantante.getEdad());
            String nacionalidad = cantante.getNacionalidad();
            String nomArtistico = cantante.getNombreArtistico();
            String genMusical = cantante.getGeneroMusical();
            String numSencillos = String.valueOf(cantante.getNumeroDeSencillos());
            String numConciertos = String.valueOf(cantante.getNumeroDeConciertos());
            String numGiras = String.valueOf(cantante.getNumeroDeGiras());
            String salario = String.valueOf(cantante.getSalario());

            Object[] rowData = {codigo, nombre, apellido, edad, nacionalidad, nomArtistico, genMusical, numSencillos, numConciertos, numGiras, salario};
            modeloCantante.addRow(rowData);
        }
        this.tblListarCliente.setModel(modeloCantante);
    }
    
    private void limpiarCamposCompositor() {
        this.txtCodigoCompositor.setText("");
        this.txtNombreCompositor.setText("");
        this.txtApellidoCompositor.setText("");
        this.txtEdadCompositor.setText("");
        this.cbxPaisesCompositor.setSelectedItem("--Selecciona un País--");
        this.txtNumComposicionesCompositor.setText("");
        this.txtSalarioCompositor.setText("");

    }
    private boolean camposObligatoriosConDatos() {
        if (!this.txtCodigoCompositor.getText().isEmpty()) {
            return true;
        } else {
            return false;
        }
    }
    private void cambiarEstadoCampos(boolean estado) {
        txtCodigoCompositor.setEnabled(!estado);

    }

    






    







    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCompositor;
    private javax.swing.JComboBox<String> cbxPaisesCompositor;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantante2;
    private javax.swing.JLabel lblFechaNacimientoCrearPersona1;
    private javax.swing.JLabel lblNacionalidadBuscarCantante1;
    private javax.swing.JLabel lblNombreCrearPersona4;
    private javax.swing.JLabel lblNombreCrearPersona5;
    private javax.swing.JLabel lblNombreCrearPersona6;
    private javax.swing.JLabel lblNumGirasBuscarCantante1;
    private javax.swing.JLabel lblSalarioBuscarCantante1;
    private javax.swing.JPanel panelCantante1;
    private javax.swing.JTable tblListarCliente;
    private javax.swing.JTextField txtApellidoCompositor;
    private javax.swing.JTextField txtCodigoCompositor;
    private javax.swing.JTextField txtEdadCompositor;
    private javax.swing.JTextField txtNombreCompositor;
    private javax.swing.JTextField txtNumComposicionesCompositor;
    private javax.swing.JTextField txtSalarioCompositor;
    // End of variables declaration//GEN-END:variables
}
