/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica_05_ssuquilanda_jabad.vista.cliente;

import ec.edu.ups.practica_05_ssuquilanda_jabad.controlador.ControladorCantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.vista.cancion.*;
import ec.edu.ups.practica_05_ssuquilanda_jabad.controlador.ControladorCompositor;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Cancion;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Cantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Compositor;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaAsignarCliente extends javax.swing.JInternalFrame {
    private ControladorCompositor controladorCompositor;
    private ControladorCantante controladorCantante;
    private ResourceBundle mensajes;
    /**
     * Creates new form VentanaIngresarCancion
     */
    public VentanaAsignarCliente(ControladorCompositor controladorCompositor) {
        initComponents();
        this.controladorCompositor = controladorCompositor;
    }
     public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jLabel3.setText(mensajes.getString("txtBuscarCompositorPorSuCódigoParaAgregarleUnCliente"));
        lblNombreCrearPersona5.setText(mensajes.getString("txtCódigo"));
        lblNombreCrearPersona4.setText(mensajes.getString("txtNombre"));        
        lblFechaNacimientoCrearPersona1.setText(mensajes.getString("txtApellido"));        
        lblNombreCrearPersona6.setText(mensajes.getString("txtEdad"));        
        lblNacionalidadBuscarCantante1.setText(mensajes.getString("txtNacionalidad"));       
        lblNumGirasBuscarCantante1.setText(mensajes.getString("txtNúmeroDeComposiciónes"));        
        lblSalarioBuscarCantante1.setText(mensajes.getString("txtSalario"));
        btnBuscarCompositor.setText(mensajes.getString("txtBuscar"));
        jLabel1.setText(mensajes.getString("txtIngresarCódigoDelClienteParaAgregar"));
        lblNombreCrearPersona2.setText(mensajes.getString("txtCódigo"));
        lblNombreCrearPersona1.setText(mensajes.getString("txtNombre"));        
        lblFechaNacimientoCrearPersona.setText(mensajes.getString("txtApellido"));        
        lblNombreCrearPersona3.setText(mensajes.getString("txtEdad"));        
        lblNacionalidadBuscarCantante.setText(mensajes.getString("txtNacionalidad"));
        lblNomArtisticoBuscarCantante.setText(mensajes.getString("txtNombreArtístico"));        
        lblGenMusicalBuscarCantante.setText(mensajes.getString("txtGéneroMusical"));        
        lblNumSencillosBuscarCantante.setText(mensajes.getString("txtNúmeroDeSencillos"));        
        lblNumConciertosBuscarCantante.setText(mensajes.getString("txtNúmeroDeConciertos"));        
        lblNumGirasBuscarCantante.setText(mensajes.getString("txtNúmeroDeGiras"));
        lblSalarioBaseBuscarCantante1.setText(mensajes.getString("txtSalarioBase"));
        lblSalarioFinalBuscarCantante.setText(mensajes.getString("txtSalarioFinal"));
        btnBuscarAsignarCantante.setText(mensajes.getString("txtBuscar"));
        btnAceptarAsignarCliente.setText(mensajes.getString("txtAceptar"));
        btnCancelarAsignarCancion.setText(mensajes.getString("txtCancelar"));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCantante1 = new javax.swing.JPanel();
        lblFechaNacimientoCrearPersona1 = new javax.swing.JLabel();
        lblNumGirasBuscarCantante1 = new javax.swing.JLabel();
        txtCodigoCompositor = new javax.swing.JTextField();
        txtNombreCompositor = new javax.swing.JTextField();
        btnBuscarCompositor = new javax.swing.JButton();
        lblCantante2 = new javax.swing.JLabel();
        lblNombreCrearPersona4 = new javax.swing.JLabel();
        lblNombreCrearPersona5 = new javax.swing.JLabel();
        lblNombreCrearPersona6 = new javax.swing.JLabel();
        lblNacionalidadBuscarCantante1 = new javax.swing.JLabel();
        txtApellidoCompositor = new javax.swing.JTextField();
        txtEdadCompositor = new javax.swing.JTextField();
        txtNumComposicionesCompositor = new javax.swing.JTextField();
        lblSalarioBuscarCantante1 = new javax.swing.JLabel();
        txtSalarioCompositor = new javax.swing.JTextField();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbxPaisesCompositor = new javax.swing.JComboBox<>();
        panelCantante = new javax.swing.JPanel();
        lblFechaNacimientoCrearPersona = new javax.swing.JLabel();
        lblNumGirasBuscarCantante = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        txtNombreCantante = new javax.swing.JTextField();
        btnBuscarAsignarCantante = new javax.swing.JButton();
        lblcantantaFondo = new javax.swing.JLabel();
        lblicono = new javax.swing.JLabel();
        lblNombreCrearPersona1 = new javax.swing.JLabel();
        lblNombreCrearPersona2 = new javax.swing.JLabel();
        lblNombreCrearPersona3 = new javax.swing.JLabel();
        lblNacionalidadBuscarCantante = new javax.swing.JLabel();
        lblNomArtisticoBuscarCantante = new javax.swing.JLabel();
        lblGenMusicalBuscarCantante = new javax.swing.JLabel();
        lblNumSencillosBuscarCantante = new javax.swing.JLabel();
        lblNumConciertosBuscarCantante = new javax.swing.JLabel();
        txtNomArtisticoCantante = new javax.swing.JTextField();
        txtApellidoCantante = new javax.swing.JTextField();
        txtEdadCantante = new javax.swing.JTextField();
        txtNumSencillosCantante = new javax.swing.JTextField();
        txtNumConciertosCantante = new javax.swing.JTextField();
        txtNumGirasCantante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblSalarioFinalBuscarCantante = new javax.swing.JLabel();
        txtSalarioFinalCantante = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        lblSalarioBaseBuscarCantante1 = new javax.swing.JLabel();
        txtSalarioCantante1 = new javax.swing.JTextField();
        cbxPaisesActualizarCantante = new javax.swing.JComboBox<>();
        cbxGeneroMusicalCantante = new javax.swing.JComboBox<>();
        btnAceptarAsignarCliente = new javax.swing.JButton();
        btnCancelarAsignarCancion = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCantante1.setBackground(new java.awt.Color(255, 255, 255));
        panelCantante1.setToolTipText("Crear Nueva Persona");
        panelCantante1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaNacimientoCrearPersona1.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblFechaNacimientoCrearPersona1.setText("Apellido:");
        panelCantante1.add(lblFechaNacimientoCrearPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, 30));

        lblNumGirasBuscarCantante1.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumGirasBuscarCantante1.setText("Num. Composiciones:");
        panelCantante1.add(lblNumGirasBuscarCantante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 220, 30));

        txtCodigoCompositor.setToolTipText("Ingrese el codigo del compositor");
        txtCodigoCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(txtCodigoCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 220, 30));

        txtNombreCompositor.setToolTipText("Ingrese el nombre del cantante");
        txtNombreCompositor.setEnabled(false);
        txtNombreCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(txtNombreCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 220, 30));

        btnBuscarCompositor.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBuscarCompositor.setText("Buscar");
        btnBuscarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(btnBuscarCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 106, 32));

        lblCantante2.setFont(new java.awt.Font("AkayaTelivigala", 1, 36)); // NOI18N
        lblCantante2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/My project-1-3.png"))); // NOI18N
        lblCantante2.setText("UPS Musik");
        lblCantante2.setPreferredSize(new java.awt.Dimension(200, 400));
        panelCantante1.add(lblCantante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 330, 50));

        lblNombreCrearPersona4.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblNombreCrearPersona4.setText("Nombre:");
        panelCantante1.add(lblNombreCrearPersona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 150, 30));

        lblNombreCrearPersona5.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona5.setText("Codigo:");
        panelCantante1.add(lblNombreCrearPersona5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, 30));

        lblNombreCrearPersona6.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona6.setText("Edad:");
        panelCantante1.add(lblNombreCrearPersona6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 78, 30));

        lblNacionalidadBuscarCantante1.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNacionalidadBuscarCantante1.setText("Nacionalidad:");
        panelCantante1.add(lblNacionalidadBuscarCantante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 230, 30));

        txtApellidoCompositor.setToolTipText("Ingrese el apellido del cantante");
        txtApellidoCompositor.setEnabled(false);
        txtApellidoCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(txtApellidoCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 220, 30));

        txtEdadCompositor.setToolTipText("Ingrese le edad del cantante");
        txtEdadCompositor.setEnabled(false);
        txtEdadCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(txtEdadCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 220, 30));

        txtNumComposicionesCompositor.setToolTipText("Ingrese el genero musical del cantante");
        txtNumComposicionesCompositor.setEnabled(false);
        txtNumComposicionesCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumComposicionesCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(txtNumComposicionesCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 220, 30));

        lblSalarioBuscarCantante1.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblSalarioBuscarCantante1.setText("Salario:");
        panelCantante1.add(lblSalarioBuscarCantante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 120, 30));

        txtSalarioCompositor.setToolTipText("Ingrese el nombre de la nueva persona");
        txtSalarioCompositor.setEnabled(false);
        txtSalarioCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(txtSalarioCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 220, 30));

        jInternalFrame2.setClosable(true);
        jInternalFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setMaximizable(true);
        jInternalFrame2.setResizable(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCantante1.add(jInternalFrame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Hoefler Text", 1, 24)); // NOI18N
        jLabel3.setText("Buscar compositor por su codigo, al cual se le va agregar un cliente :");
        panelCantante1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 920, 40));

        cbxPaisesCompositor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona un País--" }));
        cbxPaisesCompositor.setToolTipText("Puede cambiar la nacionalidad");
        cbxPaisesCompositor.setEnabled(false);
        cbxPaisesCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisesCompositorActionPerformed(evt);
            }
        });
        panelCantante1.add(cbxPaisesCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 220, 30));

        getContentPane().add(panelCantante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 314));

        panelCantante.setBackground(new java.awt.Color(255, 255, 255));
        panelCantante.setToolTipText("");
        panelCantante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaNacimientoCrearPersona.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblFechaNacimientoCrearPersona.setText("Apellido:");
        panelCantante.add(lblFechaNacimientoCrearPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 30));

        lblNumGirasBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumGirasBuscarCantante.setText("Num. Giras:");
        panelCantante.add(lblNumGirasBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 180, 30));

        txtCodigoCliente.setToolTipText("Ingrese el codigo del cantante");
        txtCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoClienteActionPerformed(evt);
            }
        });
        panelCantante.add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 220, 30));

        txtNombreCantante.setToolTipText("Este es el Nombre del cantante");
        txtNombreCantante.setEnabled(false);
        txtNombreCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNombreCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 220, 30));

        btnBuscarAsignarCantante.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBuscarAsignarCantante.setText("Buscar");
        btnBuscarAsignarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignarCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(btnBuscarAsignarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 106, 32));

        lblcantantaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/silue h.png"))); // NOI18N
        panelCantante.add(lblcantantaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 290, 360));

        lblicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpeg"))); // NOI18N
        panelCantante.add(lblicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 360, 570));

        lblNombreCrearPersona1.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblNombreCrearPersona1.setText("Nombre:");
        panelCantante.add(lblNombreCrearPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 30));

        lblNombreCrearPersona2.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona2.setText("Codigo:");
        panelCantante.add(lblNombreCrearPersona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, 30));

        lblNombreCrearPersona3.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona3.setText("Edad:");
        panelCantante.add(lblNombreCrearPersona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 78, 30));

        lblNacionalidadBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNacionalidadBuscarCantante.setText("Nacionalidad:");
        panelCantante.add(lblNacionalidadBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 30));

        lblNomArtisticoBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNomArtisticoBuscarCantante.setText("Nombre Artístico:");
        lblNomArtisticoBuscarCantante.setToolTipText("");
        panelCantante.add(lblNomArtisticoBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 210, 30));

        lblGenMusicalBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblGenMusicalBuscarCantante.setText("Género Musical:");
        panelCantante.add(lblGenMusicalBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 230, 30));

        lblNumSencillosBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumSencillosBuscarCantante.setText("Num. Sencillos:");
        panelCantante.add(lblNumSencillosBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 210, 30));

        lblNumConciertosBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumConciertosBuscarCantante.setText("Num. Conciertos:");
        panelCantante.add(lblNumConciertosBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 210, 30));

        txtNomArtisticoCantante.setToolTipText("Este es el nombre artístico del Cantante");
        txtNomArtisticoCantante.setEnabled(false);
        txtNomArtisticoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomArtisticoCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNomArtisticoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 220, 30));

        txtApellidoCantante.setToolTipText("Este es el Apellido del Cantante");
        txtApellidoCantante.setEnabled(false);
        txtApellidoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtApellidoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 220, 30));

        txtEdadCantante.setToolTipText("Esta es la edad del Cantante");
        txtEdadCantante.setEnabled(false);
        txtEdadCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtEdadCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 220, 30));

        txtNumSencillosCantante.setToolTipText("Este es el numero de Sencillos del Cantante");
        txtNumSencillosCantante.setEnabled(false);
        txtNumSencillosCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumSencillosCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNumSencillosCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 220, 30));

        txtNumConciertosCantante.setToolTipText("Este es el numero de Conciertos del Cantante");
        txtNumConciertosCantante.setEnabled(false);
        txtNumConciertosCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumConciertosCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNumConciertosCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 220, 30));

        txtNumGirasCantante.setToolTipText("Este es el numero de Giras del Cantante");
        txtNumGirasCantante.setEnabled(false);
        txtNumGirasCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumGirasCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNumGirasCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 220, 30));

        jLabel1.setFont(new java.awt.Font("Hoefler Text", 1, 24)); // NOI18N
        jLabel1.setText("Ingrese el codigo del cliente a asignarle al compositor:");
        panelCantante.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 590, 30));

        lblSalarioFinalBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblSalarioFinalBuscarCantante.setText("Salario Final:");
        panelCantante.add(lblSalarioFinalBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 220, 30));

        txtSalarioFinalCantante.setToolTipText("Este es el salario del Cantante");
        txtSalarioFinalCantante.setEnabled(false);
        txtSalarioFinalCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioFinalCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtSalarioFinalCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 220, 30));

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCantante.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblSalarioBaseBuscarCantante1.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblSalarioBaseBuscarCantante1.setText("Salario Base:");
        panelCantante.add(lblSalarioBaseBuscarCantante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 250, 30));

        txtSalarioCantante1.setToolTipText("Este es el salario del Cantante");
        txtSalarioCantante1.setEnabled(false);
        txtSalarioCantante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioCantante1ActionPerformed(evt);
            }
        });
        panelCantante.add(txtSalarioCantante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 220, 30));

        cbxPaisesActualizarCantante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona un País--" }));
        cbxPaisesActualizarCantante.setToolTipText("Puede cambiar la nacionalidad");
        cbxPaisesActualizarCantante.setEnabled(false);
        cbxPaisesActualizarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisesActualizarCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(cbxPaisesActualizarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 220, 30));

        cbxGeneroMusicalCantante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona un Género--" }));
        cbxGeneroMusicalCantante.setToolTipText("Puede cambiar el género musical");
        cbxGeneroMusicalCantante.setEnabled(false);
        cbxGeneroMusicalCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeneroMusicalCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(cbxGeneroMusicalCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 220, 30));

        btnAceptarAsignarCliente.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAceptarAsignarCliente.setText("Asignar");
        btnAceptarAsignarCliente.setEnabled(false);
        btnAceptarAsignarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarAsignarClienteActionPerformed(evt);
            }
        });
        panelCantante.add(btnAceptarAsignarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 100, 30));

        btnCancelarAsignarCancion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelarAsignarCancion.setText("Cancelar");
        btnCancelarAsignarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAsignarCancionActionPerformed(evt);
            }
        });
        panelCantante.add(btnCancelarAsignarCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 104, 32));

        getContentPane().add(panelCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 316, 940, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        this.limpiarCamposCliente();
        this.limpiarCamposCompositor();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtCodigoCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCompositorActionPerformed

    private void txtNombreCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCompositorActionPerformed

    private void btnBuscarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCompositorActionPerformed
        if (camposObligatoriosConDatos()) {
            JOptionPane.showMessageDialog(this, "El codigo del compositor a buscar no ha sido ingresado!");
        } else {
            String codigo = txtCodigoCompositor.getText();

            int codiguito = Integer.parseInt(codigo);

            Compositor compositorSeleccionado = controladorCompositor.buscarCompositor(codiguito);
            if (compositorSeleccionado != null) {
                txtNombreCompositor.setText(compositorSeleccionado.getNombre());
                txtApellidoCompositor.setText(compositorSeleccionado.getApellido());
                String edad = String.valueOf(compositorSeleccionado.getEdad());
                txtEdadCompositor.setText(edad);
                cbxPaisesCompositor.setSelectedItem(compositorSeleccionado.getNacionalidad());
                String numComposiones = String.valueOf(compositorSeleccionado.getNumeroDeComposiciones());
                txtNumComposicionesCompositor.setText(numComposiones);
                String salarioCom = String.valueOf(compositorSeleccionado.getSalario());
                txtSalarioCompositor.setText(salarioCom);
                JOptionPane.showMessageDialog(this, "El/La compositor con codigo " + codiguito + " ha sido encontrado !:(");
                btnAceptarAsignarCliente.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(this, "El/La compositor con codigo " + codiguito + " no ha sido encontrada !:(");

                this.limpiarCamposCompositor();
            }
        }
    }//GEN-LAST:event_btnBuscarCompositorActionPerformed

    private void txtApellidoCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCompositorActionPerformed

    private void txtEdadCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadCompositorActionPerformed

    private void txtNumComposicionesCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumComposicionesCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumComposicionesCompositorActionPerformed

    private void txtSalarioCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioCompositorActionPerformed

    private void btnAceptarAsignarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarAsignarClienteActionPerformed
        //Asignar cliente
        String codigoCompositor = txtCodigoCompositor.getText();
        int codiguito = Integer.parseInt(codigoCompositor);
        Compositor compositorSeleccionado = controladorCompositor.buscarCompositor(codiguito);
        Cantante cliente = controladorCantante.buscarCantante(Integer.parseInt(txtCodigoCliente.getText()));
        compositorSeleccionado.agregarCliente(cliente);
    }//GEN-LAST:event_btnAceptarAsignarClienteActionPerformed

    private void txtCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoClienteActionPerformed

    private void txtNombreCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCantanteActionPerformed

    private void btnBuscarAsignarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAsignarCantanteActionPerformed
        String codigo = txtCodigoCliente.getText();
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El codigo del cantante a buscar no ha sido ingresado!");
        } else {
            int codiguito = Integer.parseInt(codigo);

            Cantante cantante = controladorCantante.buscarCantante(codiguito);
            if (cantante != null) {
                txtNombreCantante.setText(cantante.getNombre());
                txtApellidoCantante.setText(cantante.getApellido());
                String edad = String.valueOf(cantante.getEdad());
                txtEdadCantante.setText(edad);
                cbxPaisesActualizarCantante.setSelectedItem(cantante.getNacionalidad());
                txtNomArtisticoCantante.setText(cantante.getNombreArtistico());
                cbxGeneroMusicalCantante.setSelectedItem(cantante.getGeneroMusical());
                String numSencillos = String.valueOf(cantante.getNumeroDeSencillos());
                txtNumSencillosCantante.setText(numSencillos);
                String numConciertos = String.valueOf(cantante.getNumeroDeConciertos());
                txtNumConciertosCantante.setText(numConciertos);
                String numGiras = String.valueOf(cantante.getNumeroDeGiras());
                txtNumGirasCantante.setText(numGiras);
                String salarioCan = String.valueOf(cantante.getSalario());
                String salarioCanF = String.valueOf(cantante.getSalarioFinal());
                txtSalarioFinalCantante.setText(salarioCanF);
                txtSalarioCantante1.setText(salarioCan);
                JOptionPane.showMessageDialog(this, "El/La cantante con codigo " + codiguito + " ha sido encontrado !:)");

            } else {
                JOptionPane.showMessageDialog(this, "El/La cantante con codigo " + codiguito + " no ha sido encontrada !:(");

                this.limpiarCamposCliente();
            }
        }
    }//GEN-LAST:event_btnBuscarAsignarCantanteActionPerformed

    private void txtNomArtisticoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomArtisticoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomArtisticoCantanteActionPerformed

    private void txtApellidoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCantanteActionPerformed

    private void txtEdadCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadCantanteActionPerformed

    private void txtNumSencillosCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumSencillosCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumSencillosCantanteActionPerformed

    private void txtNumConciertosCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumConciertosCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumConciertosCantanteActionPerformed

    private void txtNumGirasCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumGirasCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumGirasCantanteActionPerformed

    private void txtSalarioFinalCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioFinalCantanteActionPerformed

    }//GEN-LAST:event_txtSalarioFinalCantanteActionPerformed

    private void txtSalarioCantante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioCantante1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioCantante1ActionPerformed

    private void cbxPaisesActualizarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisesActualizarCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPaisesActualizarCantanteActionPerformed

    private void cbxGeneroMusicalCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeneroMusicalCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGeneroMusicalCantanteActionPerformed

    private void btnCancelarAsignarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAsignarCancionActionPerformed
        this.limpiarCamposCompositor();
        this.setVisible(false);
        this.limpiarCamposCliente();
    }//GEN-LAST:event_btnCancelarAsignarCancionActionPerformed

    private void cbxPaisesCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisesCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPaisesCompositorActionPerformed
    private void limpiarCamposCompositor() {
        this.txtCodigoCompositor.setText("");
        this.txtNombreCompositor.setText("");
        this.txtApellidoCompositor.setText("");
        this.txtEdadCompositor.setText("");
        this.cbxPaisesCompositor.setSelectedItem("--Selecciona un País--");
        this.txtNumComposicionesCompositor.setText("");
        this.txtSalarioCompositor.setText("");

    }

    private void limpiarCamposCliente() {
        this.txtCodigoCliente.setText("");
        this.txtNombreCantante.setText("");
        this.txtApellidoCantante.setText("");
        this.txtEdadCantante.setText("");
        this.cbxPaisesActualizarCantante.setSelectedItem("--Selecciona un País--");
        this.cbxGeneroMusicalCantante.setSelectedItem("--Selecciona un Género--");
        this.txtNomArtisticoCantante.setText("");
        this.txtNumSencillosCantante.setText("");
        this.txtNumConciertosCantante.setText("");
        this.txtNumGirasCantante.setText("");
        this.txtSalarioCantante1.setText("");
        this.txtSalarioFinalCantante.setText("");
    }

    

    private boolean camposObligatoriosConDatos() {
        if (!this.txtCodigoCliente.getText().isEmpty() && this.txtCodigoCompositor.getText().isEmpty()) {
            return true;
        } else {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarAsignarCliente;
    private javax.swing.JButton btnBuscarAsignarCantante;
    private javax.swing.JButton btnBuscarCompositor;
    private javax.swing.JButton btnCancelarAsignarCancion;
    private javax.swing.JComboBox<String> cbxGeneroMusicalCantante;
    private javax.swing.JComboBox<String> cbxPaisesActualizarCantante;
    private javax.swing.JComboBox<String> cbxPaisesCompositor;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCantante2;
    private javax.swing.JLabel lblFechaNacimientoCrearPersona;
    private javax.swing.JLabel lblFechaNacimientoCrearPersona1;
    private javax.swing.JLabel lblGenMusicalBuscarCantante;
    private javax.swing.JLabel lblNacionalidadBuscarCantante;
    private javax.swing.JLabel lblNacionalidadBuscarCantante1;
    private javax.swing.JLabel lblNomArtisticoBuscarCantante;
    private javax.swing.JLabel lblNombreCrearPersona1;
    private javax.swing.JLabel lblNombreCrearPersona2;
    private javax.swing.JLabel lblNombreCrearPersona3;
    private javax.swing.JLabel lblNombreCrearPersona4;
    private javax.swing.JLabel lblNombreCrearPersona5;
    private javax.swing.JLabel lblNombreCrearPersona6;
    private javax.swing.JLabel lblNumConciertosBuscarCantante;
    private javax.swing.JLabel lblNumGirasBuscarCantante;
    private javax.swing.JLabel lblNumGirasBuscarCantante1;
    private javax.swing.JLabel lblNumSencillosBuscarCantante;
    private javax.swing.JLabel lblSalarioBaseBuscarCantante1;
    private javax.swing.JLabel lblSalarioBuscarCantante1;
    private javax.swing.JLabel lblSalarioFinalBuscarCantante;
    private javax.swing.JLabel lblcantantaFondo;
    private javax.swing.JLabel lblicono;
    private javax.swing.JPanel panelCantante;
    private javax.swing.JPanel panelCantante1;
    private javax.swing.JTextField txtApellidoCantante;
    private javax.swing.JTextField txtApellidoCompositor;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtCodigoCompositor;
    private javax.swing.JTextField txtEdadCantante;
    private javax.swing.JTextField txtEdadCompositor;
    private javax.swing.JTextField txtNomArtisticoCantante;
    private javax.swing.JTextField txtNombreCantante;
    private javax.swing.JTextField txtNombreCompositor;
    private javax.swing.JTextField txtNumComposicionesCompositor;
    private javax.swing.JTextField txtNumConciertosCantante;
    private javax.swing.JTextField txtNumGirasCantante;
    private javax.swing.JTextField txtNumSencillosCantante;
    private javax.swing.JTextField txtSalarioCantante1;
    private javax.swing.JTextField txtSalarioCompositor;
    private javax.swing.JTextField txtSalarioFinalCantante;
    // End of variables declaration//GEN-END:variables
}
