/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica_05_ssuquilanda_jabad.vista.disco;

import ec.edu.ups.practica_05_ssuquilanda_jabad.controlador.ControladorCantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Cantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Disco;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaIngresarDisco extends javax.swing.JInternalFrame {

    private ControladorCantante controladorCantante;
    private ResourceBundle mensajes;
    /**
     * Creates new form VentanaCrearDisco
     */
    public VentanaIngresarDisco(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
    }
     public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jLabel1.setText(mensajes.getString("BuscarCantantePorSuCódigoParaAgregarleElÁlbum "));
        jLabel2.setText(mensajes.getString("txtIngresarLosDatosDelDiscoACrear"));
        lblCodigoCantanteDisco.setText(mensajes.getString("txtCódigo"));
        lblNombreCantanteDisco.setText(mensajes.getString("txtNombre"));        
        lblApellidoDisco.setText(mensajes.getString("txtApellido"));        
        lblEdadDisco.setText(mensajes.getString("txtEdad"));        
        lblNacionalidaddisco.setText(mensajes.getString("txtNacionalidad"));   
        lblNombreArtDisco.setText(mensajes.getString("txtNombreArtístico"));        
        lblGenroDisco.setText(mensajes.getString("txtGéneroMusical"));        
        lblNumSencillosDisco.setText(mensajes.getString("txtNúmeroDeSencillos"));        
        lblNumConciertosDisco.setText(mensajes.getString("txtNúmeroDeConciertos"));        
        lblNumGirasDisco.setText(mensajes.getString("txtNúmeroDeGiras"));        
        lblSalarioDisco.setText(mensajes.getString("txtSalarioBase"));
        lblCodigoDisco.setText(mensajes.getString("txtCódigo"));
        lblNombreDisco.setText(mensajes.getString("txtNombre"));
        btnAceptarDisco.setText(mensajes.getString("txtEliminar"));
        btnBuscarCantante.setText(mensajes.getString("txtBuscar"));
        btnCancelarCantante.setText(mensajes.getString("txtCancelar"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCantante = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelCantante1 = new javax.swing.JPanel();
        lblApellidoDisco = new javax.swing.JLabel();
        lblNumGirasDisco = new javax.swing.JLabel();
        txtCodigoCantante = new javax.swing.JTextField();
        txtNombreCantante = new javax.swing.JTextField();
        btnBuscarCantante = new javax.swing.JButton();
        lblCantante2 = new javax.swing.JLabel();
        lblNombreCantanteDisco = new javax.swing.JLabel();
        lblCodigoCantanteDisco = new javax.swing.JLabel();
        lblEdadDisco = new javax.swing.JLabel();
        lblNacionalidaddisco = new javax.swing.JLabel();
        lblNombreArtDisco = new javax.swing.JLabel();
        lblGenroDisco = new javax.swing.JLabel();
        lblNumSencillosDisco = new javax.swing.JLabel();
        lblNumConciertosDisco = new javax.swing.JLabel();
        txtNomArtisticoCantante = new javax.swing.JTextField();
        txtApellidoCantante = new javax.swing.JTextField();
        txtEdadCantante = new javax.swing.JTextField();
        txtNacionalidadCantante = new javax.swing.JTextField();
        txtGeneroMusicalCantante = new javax.swing.JTextField();
        txtNumSencillosCantante = new javax.swing.JTextField();
        txtNumConciertosCantante = new javax.swing.JTextField();
        txtNumGirasCantante = new javax.swing.JTextField();
        lblSalarioDisco = new javax.swing.JLabel();
        txtSalarioCantante = new javax.swing.JTextField();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCancelarCantante = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblCodigoDisco = new javax.swing.JLabel();
        lblNombreDisco = new javax.swing.JLabel();
        lblAñoDeLanzamientoDisco = new javax.swing.JLabel();
        txtAñoDeLanzamientoIngresarDisco = new javax.swing.JTextField();
        txtNombreDisco = new javax.swing.JTextField();
        txtCodigoDisco = new javax.swing.JTextField();
        btnAceptarDisco = new javax.swing.JButton();
        lblicono1 = new javax.swing.JLabel();
        lblcantantaFondo1 = new javax.swing.JLabel();

        lblCantante.setFont(new java.awt.Font("AkayaTelivigala", 1, 36)); // NOI18N
        lblCantante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/My project-1-3.png"))); // NOI18N
        lblCantante.setText("UPS Musik");
        lblCantante.setPreferredSize(new java.awt.Dimension(200, 400));

        setBorder(javax.swing.BorderFactory.createTitledBorder("Crear discos para agregar a un cantante"));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelCantante1.setBackground(new java.awt.Color(255, 255, 255));
        panelCantante1.setToolTipText("Crear Nueva Persona");
        panelCantante1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblApellidoDisco.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblApellidoDisco.setText("Apellido:");
        panelCantante1.add(lblApellidoDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 30));

        lblNumGirasDisco.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumGirasDisco.setText("Num. Giras:");
        panelCantante1.add(lblNumGirasDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 180, 30));

        txtCodigoCantante.setToolTipText("Ingrese el codigo del cantante");
        txtCodigoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCantanteActionPerformed(evt);
            }
        });
        panelCantante1.add(txtCodigoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 220, 30));

        txtNombreCantante.setToolTipText("Ingrese el nombre del cantante");
        txtNombreCantante.setEnabled(false);
        txtNombreCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCantanteActionPerformed(evt);
            }
        });
        panelCantante1.add(txtNombreCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 220, 30));

        btnBuscarCantante.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBuscarCantante.setText("Buscar");
        btnBuscarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCantanteActionPerformed(evt);
            }
        });
        panelCantante1.add(btnBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 106, 32));

        lblCantante2.setFont(new java.awt.Font("AkayaTelivigala", 1, 36)); // NOI18N
        lblCantante2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/My project-1-3.png"))); // NOI18N
        lblCantante2.setText("UPS Musik");
        lblCantante2.setPreferredSize(new java.awt.Dimension(200, 400));
        panelCantante1.add(lblCantante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 330, 50));

        lblNombreCantanteDisco.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblNombreCantanteDisco.setText("Nombre:");
        panelCantante1.add(lblNombreCantanteDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 30));

        lblCodigoCantanteDisco.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblCodigoCantanteDisco.setText("Codigo:");
        panelCantante1.add(lblCodigoCantanteDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        lblEdadDisco.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblEdadDisco.setText("Edad:");
        panelCantante1.add(lblEdadDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 78, 30));

        lblNacionalidaddisco.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNacionalidaddisco.setText("Nacionalidad:");
        panelCantante1.add(lblNacionalidaddisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 220, 30));

        lblNombreArtDisco.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreArtDisco.setText("Nombre Artistico:");
        panelCantante1.add(lblNombreArtDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, 30));

        lblGenroDisco.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblGenroDisco.setText("Genero Musical:");
        panelCantante1.add(lblGenroDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 230, 30));

        lblNumSencillosDisco.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumSencillosDisco.setText("Num. Sencillos:");
        panelCantante1.add(lblNumSencillosDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 220, 30));

        lblNumConciertosDisco.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumConciertosDisco.setText("Num. Conciertos:");
        panelCantante1.add(lblNumConciertosDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 210, 30));

        txtNomArtisticoCantante.setToolTipText("Ingrese el nombre artistico del cantante");
        txtNomArtisticoCantante.setEnabled(false);
        txtNomArtisticoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomArtisticoCantanteActionPerformed(evt);
            }
        });
        panelCantante1.add(txtNomArtisticoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 220, 30));

        txtApellidoCantante.setToolTipText("Ingrese el apellido del cantante");
        txtApellidoCantante.setEnabled(false);
        txtApellidoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCantanteActionPerformed(evt);
            }
        });
        panelCantante1.add(txtApellidoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 220, 30));

        txtEdadCantante.setToolTipText("Ingrese le edad del cantante");
        txtEdadCantante.setEnabled(false);
        txtEdadCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadCantanteActionPerformed(evt);
            }
        });
        panelCantante1.add(txtEdadCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 220, 30));

        txtNacionalidadCantante.setToolTipText("Ingrese la nacionalidad del cantante");
        txtNacionalidadCantante.setEnabled(false);
        txtNacionalidadCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacionalidadCantanteActionPerformed(evt);
            }
        });
        panelCantante1.add(txtNacionalidadCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 220, 30));

        txtGeneroMusicalCantante.setToolTipText("Ingrese el genero musical del cantante");
        txtGeneroMusicalCantante.setEnabled(false);
        txtGeneroMusicalCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroMusicalCantanteActionPerformed(evt);
            }
        });
        panelCantante1.add(txtGeneroMusicalCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 220, 30));

        txtNumSencillosCantante.setToolTipText("Ingrese el numero de sencillos del cantante");
        txtNumSencillosCantante.setEnabled(false);
        txtNumSencillosCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumSencillosCantanteActionPerformed(evt);
            }
        });
        panelCantante1.add(txtNumSencillosCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 220, 30));

        txtNumConciertosCantante.setToolTipText("Ingrese el numero de conciertos dados por el cantante");
        txtNumConciertosCantante.setEnabled(false);
        txtNumConciertosCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumConciertosCantanteActionPerformed(evt);
            }
        });
        panelCantante1.add(txtNumConciertosCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 220, 30));

        txtNumGirasCantante.setToolTipText("Ingrese el numero de giras del cantante");
        txtNumGirasCantante.setEnabled(false);
        txtNumGirasCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumGirasCantanteActionPerformed(evt);
            }
        });
        panelCantante1.add(txtNumGirasCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 220, 30));

        lblSalarioDisco.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblSalarioDisco.setText("Salario:");
        panelCantante1.add(lblSalarioDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 120, 30));

        txtSalarioCantante.setToolTipText("Ingrese el nombre de la nueva persona");
        txtSalarioCantante.setEnabled(false);
        txtSalarioCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioCantanteActionPerformed(evt);
            }
        });
        panelCantante1.add(txtSalarioCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 220, 30));

        jInternalFrame2.setClosable(true);
        jInternalFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setMaximizable(true);
        jInternalFrame2.setResizable(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCantante1.add(jInternalFrame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Hoefler Text", 1, 24)); // NOI18N
        jLabel1.setText("Buscar cantante por su codigo, al cual se le va agregar el disco  :");
        panelCantante1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 920, 40));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelarCantante.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelarCantante.setText("Cancelar");
        btnCancelarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCantanteActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 104, 32));

        jLabel2.setFont(new java.awt.Font("Hoefler Text", 1, 24)); // NOI18N
        jLabel2.setText("Ingresar los datos del disco a crear :");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 920, 40));

        lblCodigoDisco.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblCodigoDisco.setText("Codigo:");
        jPanel4.add(lblCodigoDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 30));

        lblNombreDisco.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblNombreDisco.setText("Nombre:");
        jPanel4.add(lblNombreDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 30));

        lblAñoDeLanzamientoDisco.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblAñoDeLanzamientoDisco.setText("Año de Lanzamiento:");
        jPanel4.add(lblAñoDeLanzamientoDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 280, 30));

        txtAñoDeLanzamientoIngresarDisco.setToolTipText("Ingrese el año de lanzamiento del disco");
        txtAñoDeLanzamientoIngresarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAñoDeLanzamientoIngresarDiscoActionPerformed(evt);
            }
        });
        jPanel4.add(txtAñoDeLanzamientoIngresarDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 250, 30));

        txtNombreDisco.setToolTipText("Ingrese el nombre del disco");
        txtNombreDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDiscoActionPerformed(evt);
            }
        });
        jPanel4.add(txtNombreDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 250, 30));

        txtCodigoDisco.setToolTipText("Ingrese el codigo del disco");
        txtCodigoDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDiscoActionPerformed(evt);
            }
        });
        jPanel4.add(txtCodigoDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 250, 30));

        btnAceptarDisco.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAceptarDisco.setText("Aceptar");
        btnAceptarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarDiscoActionPerformed(evt);
            }
        });
        jPanel4.add(btnAceptarDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 100, 30));

        lblicono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disco.png"))); // NOI18N
        jPanel4.add(lblicono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 290, 300));

        lblcantantaFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpeg"))); // NOI18N
        jPanel4.add(lblcantantaFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 320, 300));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCantante1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelCantante1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCantanteActionPerformed

    private void txtNombreCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCantanteActionPerformed

    private void btnBuscarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCantanteActionPerformed
        if (camposObligatoriosConDatos()) {
            JOptionPane.showMessageDialog(this, "El codigo del cantante a buscar no ha sido ingresado!");
        } else {
            String codigo = txtCodigoCantante.getText();

            int codiguito = Integer.parseInt(codigo);

            Cantante cantanteSeleccionado = controladorCantante.buscarCantante(codiguito);
            if (cantanteSeleccionado != null) {
                txtNombreCantante.setText(cantanteSeleccionado.getNombre());
                txtApellidoCantante.setText(cantanteSeleccionado.getApellido());
                String edad = String.valueOf(cantanteSeleccionado.getEdad());
                txtEdadCantante.setText(edad);
                txtNacionalidadCantante.setText(cantanteSeleccionado.getNacionalidad());
                txtNomArtisticoCantante.setText(cantanteSeleccionado.getNombreArtistico());
                txtGeneroMusicalCantante.setText(cantanteSeleccionado.getGeneroMusical());
                String numSencillos = String.valueOf(cantanteSeleccionado.getNumeroDeSencillos());
                txtNumSencillosCantante.setText(numSencillos);
                String numConciertos = String.valueOf(cantanteSeleccionado.getNumeroDeConciertos());
                txtNumConciertosCantante.setText(numConciertos);
                String numGiras = String.valueOf(cantanteSeleccionado.getNumeroDeGiras());
                txtNumGirasCantante.setText(numGiras);
                String salarioCan = String.valueOf(cantanteSeleccionado.getSalario());
                txtSalarioCantante.setText(salarioCan);
                JOptionPane.showMessageDialog(this, "El/La cantante con codigo " + codiguito + " ha sido encontrado !:D");
                btnAceptarDisco.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(this, "El/La cantante con codigo " + codiguito + " no ha sido encontrada !:(");

                this.limpiarCamposCantante();
            }
        }
    }//GEN-LAST:event_btnBuscarCantanteActionPerformed

    private void btnCancelarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCantanteActionPerformed
        this.limpiarCamposCantante();
        this.setVisible(false);
        this.limpiarCamposDisco();
    }//GEN-LAST:event_btnCancelarCantanteActionPerformed

    private void txtNomArtisticoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomArtisticoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomArtisticoCantanteActionPerformed

    private void txtApellidoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCantanteActionPerformed

    private void txtEdadCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadCantanteActionPerformed

    private void txtNacionalidadCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadCantanteActionPerformed

    private void txtGeneroMusicalCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroMusicalCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroMusicalCantanteActionPerformed

    private void txtNumSencillosCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumSencillosCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumSencillosCantanteActionPerformed

    private void txtNumConciertosCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumConciertosCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumConciertosCantanteActionPerformed

    private void txtNumGirasCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumGirasCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumGirasCantanteActionPerformed

    private void txtSalarioCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioCantanteActionPerformed

    private void txtAñoDeLanzamientoIngresarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñoDeLanzamientoIngresarDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoDeLanzamientoIngresarDiscoActionPerformed

    private void txtNombreDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDiscoActionPerformed

    private void txtCodigoDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDiscoActionPerformed

    private void btnAceptarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarDiscoActionPerformed
        if (camposObligatoriosConDatos()) {
            JOptionPane.showMessageDialog(this, "Los datos del disco son obligatorios de llenar");

        } else {
            String codigo = txtCodigoDisco.getText();
            int codigoDisco = Integer.parseInt(codigo);
            String nombreDisco = txtNombreDisco.getText();
            String anioDeLanzamiento = txtAñoDeLanzamientoIngresarDisco.getText();
            int anioLanzamientoDisco = Integer.parseInt(anioDeLanzamiento);
            String codigoCantante = txtCodigoCantante.getText();
            int codiguito = Integer.parseInt(codigoCantante);
            Cantante cantanteSeleccionado = controladorCantante.buscarCantante(codiguito);
            if (cantanteSeleccionado != null) {
                Disco disquito = new Disco();
                disquito.setCodigo(codigoDisco);
                disquito.setNombre(nombreDisco);
                disquito.setAnioDeLanzamiento(anioLanzamientoDisco);
                controladorCantante.agregarDisco(cantanteSeleccionado, disquito);
                this.limpiarCamposCantante();
                this.limpiarCamposDisco();
                JOptionPane.showMessageDialog(this, "El disco  ha sido creado y agregado exitosamente !:)");

            }
        }
    }//GEN-LAST:event_btnAceptarDiscoActionPerformed
    private void limpiarCamposCantante() {
        this.txtCodigoCantante.setText("");
        this.txtNombreCantante.setText("");
        this.txtApellidoCantante.setText("");
        this.txtEdadCantante.setText("");
        this.txtNacionalidadCantante.setText("");
        this.txtGeneroMusicalCantante.setText("");
        this.txtNomArtisticoCantante.setText("");
        this.txtNumSencillosCantante.setText("");
        this.txtNumConciertosCantante.setText("");
        this.txtNumGirasCantante.setText("");
        this.txtSalarioCantante.setText("");

    }

    private void limpiarCamposDisco() {
        this.txtCodigoDisco.setText("");
        this.txtNombreDisco.setText("");
        this.txtAñoDeLanzamientoIngresarDisco.setText("");

    }

    private boolean camposObligatoriosConDatos() {
        if (!this.txtCodigoDisco.getText().isEmpty() && this.txtNombreDisco.getText().isEmpty() && this.txtAñoDeLanzamientoIngresarDisco.getText().isEmpty()) {
            return true;
        } else {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarDisco;
    private javax.swing.JButton btnBuscarCantante;
    private javax.swing.JButton btnCancelarCantante;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblApellidoDisco;
    private javax.swing.JLabel lblAñoDeLanzamientoDisco;
    private javax.swing.JLabel lblCantante;
    private javax.swing.JLabel lblCantante2;
    private javax.swing.JLabel lblCodigoCantanteDisco;
    private javax.swing.JLabel lblCodigoDisco;
    private javax.swing.JLabel lblEdadDisco;
    private javax.swing.JLabel lblGenroDisco;
    private javax.swing.JLabel lblNacionalidaddisco;
    private javax.swing.JLabel lblNombreArtDisco;
    private javax.swing.JLabel lblNombreCantanteDisco;
    private javax.swing.JLabel lblNombreDisco;
    private javax.swing.JLabel lblNumConciertosDisco;
    private javax.swing.JLabel lblNumGirasDisco;
    private javax.swing.JLabel lblNumSencillosDisco;
    private javax.swing.JLabel lblSalarioDisco;
    private javax.swing.JLabel lblcantantaFondo1;
    private javax.swing.JLabel lblicono1;
    private javax.swing.JPanel panelCantante1;
    private javax.swing.JTextField txtApellidoCantante;
    private javax.swing.JTextField txtAñoDeLanzamientoIngresarDisco;
    private javax.swing.JTextField txtCodigoCantante;
    private javax.swing.JTextField txtCodigoDisco;
    private javax.swing.JTextField txtEdadCantante;
    private javax.swing.JTextField txtGeneroMusicalCantante;
    private javax.swing.JTextField txtNacionalidadCantante;
    private javax.swing.JTextField txtNomArtisticoCantante;
    private javax.swing.JTextField txtNombreCantante;
    private javax.swing.JTextField txtNombreDisco;
    private javax.swing.JTextField txtNumConciertosCantante;
    private javax.swing.JTextField txtNumGirasCantante;
    private javax.swing.JTextField txtNumSencillosCantante;
    private javax.swing.JTextField txtSalarioCantante;
    // End of variables declaration//GEN-END:variables
}
