/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica_05_ssuquilanda_jabad.vista.cantante;

import ec.edu.ups.practica_05_ssuquilanda_jabad.controlador.ControladorCantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Cancion;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Cantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Compositor;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Disco;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaListarCantante extends javax.swing.JInternalFrame {

    private ControladorCantante controladorCantante;
    private ResourceBundle mensajes;

    /**
     * Creates new form VentanaListarCantante
     */
    public VentanaListarCantante(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
        
    }
    public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jLabel2.setText(mensajes.getString("txtListaDeDiscos"));
        jLabel5.setText(mensajes.getString("txtInstruccionListarCantante1"));
        jLabel3.setText(mensajes.getString("txtListaDeCantantes"));
        btnBuscarCantante.setText(mensajes.getString("txtBuscar"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCantante = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarCantante = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListarDiscoListarCantante = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoBuscarCantante = new javax.swing.JTextField();
        btnBuscarCantante = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 90, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCantante.setFont(new java.awt.Font("AkayaTelivigala", 1, 36)); // NOI18N
        lblCantante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/My project-1-3.png"))); // NOI18N
        lblCantante.setText("UPS Musik");
        lblCantante.setPreferredSize(new java.awt.Dimension(200, 400));
        jPanel2.add(lblCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 460, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/silue h.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -10, 180, 270));

        tblListarCantante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Edad", "Nacionalidad", "Nombre Artistico", "Genero Musical", "Numero Sencillos", "Numero Conciertos", "Numero Giras", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListarCantante);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 1350, -1));

        tblListarDiscoListarCantante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Año de Lanzamiento"
            }
        ));
        jScrollPane2.setViewportView(tblListarDiscoListarCantante);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, 630, -1));

        jLabel2.setFont(new java.awt.Font("AkayaKanadaka", 1, 24)); // NOI18N
        jLabel2.setText("Lista de Discos:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 240, 50));

        jLabel3.setFont(new java.awt.Font("AkayaKanadaka", 1, 24)); // NOI18N
        jLabel3.setText("Lista de Cantantes:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 240, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disco.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 500, 470));

        jLabel5.setFont(new java.awt.Font("Al Bayan", 1, 14)); // NOI18N
        jLabel5.setText("Ingrese el codigo del cantante del cual se va a mostrar la lista de discos:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, -1, -1));

        txtCodigoBuscarCantante.setToolTipText("Ingrese el codigo del cantante a buscar");
        txtCodigoBuscarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBuscarCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodigoBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 310, -1));

        btnBuscarCantante.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBuscarCantante.setText("Buscar");
        btnBuscarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        this.cargarDatosTablaCantante();
        this.cargarDatosTablaDiscos();
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnBuscarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCantanteActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoBuscarCantante.getText();
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El codigo del  cantante a buscar no ha sido ingresado!");
        } else {
            int codiguito = Integer.parseInt(codigo);
            Cantante cantante = controladorCantante.buscarCantante(codiguito);
            if (cantante != null) {
                this.cargarDatosTablaDiscos();
            }
            }
    }//GEN-LAST:event_btnBuscarCantanteActionPerformed

    private void txtCodigoBuscarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBuscarCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBuscarCantanteActionPerformed
    private void cargarDatosTablaCantante() {
        DefaultTableModel modeloCantante = (DefaultTableModel) this.tblListarCantante.getModel();
        modeloCantante.setNumRows(0);
        List<Cantante> listaCantantes = controladorCantante.listarCantantes();
        for (Cantante cantante : listaCantantes) {

            String codigo = String.valueOf(cantante.getCodigo());
            String nombre = cantante.getNombre();
            String apellido = cantante.getApellido();
            String edad = String.valueOf(cantante.getEdad());
            String nacionalidad = cantante.getNacionalidad();
            String nomArtistico = cantante.getNombreArtistico();
            String genMusical = cantante.getGeneroMusical();
            String numSencillos = String.valueOf(cantante.getNumeroDeSencillos());
            String numConciertos = String.valueOf(cantante.getNumeroDeConciertos());
            String numGiras = String.valueOf(cantante.getNumeroDeGiras());
            String salario = String.valueOf(cantante.getSalario());

            Object[] rowData = {codigo, nombre, apellido, edad, nacionalidad, nomArtistico, genMusical, numSencillos, numConciertos, numGiras, salario};
            modeloCantante.addRow(rowData);
        }
        this.tblListarCantante.setModel(modeloCantante);
    }
    private void cargarDatosTablaDiscos() {
        DefaultTableModel modelo = (DefaultTableModel) this.tblListarDiscoListarCantante.getModel();
        modelo.setNumRows(0);
        String codigoCantante = txtCodigoBuscarCantante.getText();
        int codiguito = Integer.parseInt(codigoCantante);
        Cantante cantanteSeleccionado = controladorCantante.buscarCantante(codiguito);
        
        List<Disco> discografia = controladorCantante.discografia(cantanteSeleccionado);
        for (Disco disco : discografia) {

            String codigo = String.valueOf(disco.getCodigo());
            String nombre = disco.getNombre();
            String anioLanzamiento = String.valueOf(disco.getAnioDeLanzamiento());

            Object[] rowData = {codigo, nombre, anioLanzamiento};
            modelo.addRow(rowData);
        }
        this.tblListarDiscoListarCantante.setModel(modelo);
    }

    






    







    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCantante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantante;
    private javax.swing.JTable tblListarCantante;
    private javax.swing.JTable tblListarDiscoListarCantante;
    private javax.swing.JTextField txtCodigoBuscarCantante;
    // End of variables declaration//GEN-END:variables
}
