package ec.edu.ups.practica_05_ssuquilanda_jabad.vista.cantante;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
import ec.edu.ups.practica_05_ssuquilanda_jabad.controlador.ControladorCantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Cantante;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaCrearCantante extends javax.swing.JInternalFrame {

    private ControladorCantante controladorCantante;
    private ResourceBundle mensajes;
    /**
     * Creates new form VentanaCrearPersona
     */
    public VentanaCrearCantante(ControladorCantante controladorCantante) {

        initComponents();
        this.controladorCantante = controladorCantante;
    }
    
    public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jLabel1.setText(mensajes.getString("txtCrearCantante"));
        lblCodigoCrearPersona.setText(mensajes.getString("txtCódigo"));
        lblNombreCrearPersona1.setText(mensajes.getString("txtNombre"));        
        lblApellidoCreacCantante.setText(mensajes.getString("txtApellido"));        
        lblEdadCrearCantante.setText(mensajes.getString("txtEdad"));        
        lblNacionalidadCrearCantante.setText(mensajes.getString("txtNacionalidad"));
        cbxPaisCrearCantante.setSelectedItem(mensajes.getString("txtSeleccionarPaís"));
        cbxGeneroCrearCantante.setSelectedItem(mensajes.getString("txtSeleccionarGénero"));
        lblNombreArtCrearCantante.setText(mensajes.getString("txtNombreArtístico"));        
        lblGeneroMuscCrearCantante.setText(mensajes.getString("txtGéneroMusical"));        
        lblNumSencillosCrearCantante.setText(mensajes.getString("txtNúmeroDeSencillos"));        
        lblNumConcCrearCantante.setText(mensajes.getString("txtNúmeroDeConciertos"));        
        lblNumGirasCrearCantante.setText(mensajes.getString("txtNúmeroDeGiras"));        
        lblSalarioBaseCrearCantante.setText(mensajes.getString("txtSalarioBase"));
        btnAceptarCantante.setText(mensajes.getString("txtAceptar"));
        btnCancelarCantante.setText(mensajes.getString("txtCancelar"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCantante = new javax.swing.JPanel();
        lblApellidoCreacCantante = new javax.swing.JLabel();
        lblNumGirasCrearCantante = new javax.swing.JLabel();
        txtCodigoCantante = new javax.swing.JTextField();
        txtNombreCantante = new javax.swing.JTextField();
        btnAceptarCantante = new javax.swing.JButton();
        btnCancelarCantante = new javax.swing.JButton();
        lblicono = new javax.swing.JLabel();
        lblcantantaFondo = new javax.swing.JLabel();
        lblCantante = new javax.swing.JLabel();
        lblNombreCrearPersona1 = new javax.swing.JLabel();
        lblCodigoCrearPersona = new javax.swing.JLabel();
        lblEdadCrearCantante = new javax.swing.JLabel();
        lblNacionalidadCrearCantante = new javax.swing.JLabel();
        lblNombreArtCrearCantante = new javax.swing.JLabel();
        lblGeneroMuscCrearCantante = new javax.swing.JLabel();
        lblNumSencillosCrearCantante = new javax.swing.JLabel();
        lblNumConcCrearCantante = new javax.swing.JLabel();
        txtNomArtisticoCantante = new javax.swing.JTextField();
        txtApellidoCantante = new javax.swing.JTextField();
        txtEdadCantante = new javax.swing.JTextField();
        txtNumSencillosCantante = new javax.swing.JTextField();
        txtNumConciertosCantante = new javax.swing.JTextField();
        txtNumGirasCantante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblSalarioBaseCrearCantante = new javax.swing.JLabel();
        txtSalarioCantante = new javax.swing.JTextField();
        cbxPaisCrearCantante = new javax.swing.JComboBox<>();
        cbxGeneroCrearCantante = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Datos Crear Cantante"));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelCantante.setBackground(new java.awt.Color(255, 255, 255));
        panelCantante.setToolTipText("Crear Nueva Persona");
        panelCantante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblApellidoCreacCantante.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblApellidoCreacCantante.setText("Apellido:");
        panelCantante.add(lblApellidoCreacCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 30));

        lblNumGirasCrearCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumGirasCrearCantante.setText("Num. Giras:");
        panelCantante.add(lblNumGirasCrearCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 230, 30));

        txtCodigoCantante.setToolTipText("Ingrese el codigo del cantante");
        txtCodigoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtCodigoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 240, 30));

        txtNombreCantante.setToolTipText("Ingrese el nombre del cantante");
        txtNombreCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNombreCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 240, 30));

        btnAceptarCantante.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAceptarCantante.setText("Aceptar");
        btnAceptarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(btnAceptarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 106, 32));

        btnCancelarCantante.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelarCantante.setText("Cancelar");
        btnCancelarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(btnCancelarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 104, 32));

        lblicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/silue h.png"))); // NOI18N
        panelCantante.add(lblicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 230, 500));

        lblcantantaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpeg"))); // NOI18N
        lblcantantaFondo.setText("jLabel1");
        panelCantante.add(lblcantantaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 290, 650));

        lblCantante.setFont(new java.awt.Font("AkayaTelivigala", 1, 36)); // NOI18N
        lblCantante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/My project-1-3.png"))); // NOI18N
        lblCantante.setText("UPS Musik");
        lblCantante.setPreferredSize(new java.awt.Dimension(200, 400));
        panelCantante.add(lblCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 330, 50));

        lblNombreCrearPersona1.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblNombreCrearPersona1.setText("Nombre:");
        panelCantante.add(lblNombreCrearPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 30));

        lblCodigoCrearPersona.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblCodigoCrearPersona.setText("Codigo:");
        panelCantante.add(lblCodigoCrearPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, 30));

        lblEdadCrearCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblEdadCrearCantante.setText("Edad:");
        panelCantante.add(lblEdadCrearCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 30));

        lblNacionalidadCrearCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNacionalidadCrearCantante.setText("Nacionalidad:");
        panelCantante.add(lblNacionalidadCrearCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 170, 30));

        lblNombreArtCrearCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreArtCrearCantante.setText("Nombre Artístico:");
        panelCantante.add(lblNombreArtCrearCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 240, 30));

        lblGeneroMuscCrearCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblGeneroMuscCrearCantante.setText("Género Musical:");
        panelCantante.add(lblGeneroMuscCrearCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 230, 30));

        lblNumSencillosCrearCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumSencillosCrearCantante.setText("Num. Sencillos:");
        panelCantante.add(lblNumSencillosCrearCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 250, 30));

        lblNumConcCrearCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumConcCrearCantante.setText("Num. Conciertos:");
        panelCantante.add(lblNumConcCrearCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 230, 30));

        txtNomArtisticoCantante.setToolTipText("Ingrese el nombre artistico del cantante");
        txtNomArtisticoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomArtisticoCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNomArtisticoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 240, 30));

        txtApellidoCantante.setToolTipText("Ingrese el apellido del cantante");
        txtApellidoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtApellidoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 240, 30));

        txtEdadCantante.setToolTipText("Ingrese le edad del cantante");
        txtEdadCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtEdadCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 240, 30));

        txtNumSencillosCantante.setToolTipText("Ingrese el numero de sencillos del cantante");
        txtNumSencillosCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumSencillosCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNumSencillosCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 240, 30));

        txtNumConciertosCantante.setToolTipText("Ingrese el numero de conciertos dados por el cantante");
        txtNumConciertosCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumConciertosCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNumConciertosCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 240, 30));

        txtNumGirasCantante.setToolTipText("Ingrese el numero de giras del cantante");
        txtNumGirasCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumGirasCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNumGirasCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 240, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Crear Cantante:");
        panelCantante.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 110, 30));

        lblSalarioBaseCrearCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblSalarioBaseCrearCantante.setText("Salario Base:");
        panelCantante.add(lblSalarioBaseCrearCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 220, 30));

        txtSalarioCantante.setToolTipText("Ingrese el salario del Cantante");
        txtSalarioCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtSalarioCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 240, 30));

        cbxPaisCrearCantante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona un País--" }));
        cbxPaisCrearCantante.setToolTipText("Selecciona la nacionalidad del Cantante");
        panelCantante.add(cbxPaisCrearCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 240, 30));

        cbxGeneroCrearCantante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona un género--" }));
        cbxGeneroCrearCantante.setToolTipText("Selecciona el genero del cantante");
        panelCantante.add(cbxGeneroCrearCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCantante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCantante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCantanteActionPerformed
        if (camposObligatoriosConDatos()) {

            String codigo = txtCodigoCantante.getText();
            int codiguito = Integer.parseInt(codigo);
            String nombre = txtNombreCantante.getText();
            String apellido = txtApellidoCantante.getText();
            String edad = txtEdadCantante.getText();
            int edadcita = Integer.parseInt(edad);
            String nacionalidad = (String) cbxPaisCrearCantante.getSelectedItem();
            String nombreArtistico = txtNomArtisticoCantante.getText();
            String generoMusical = (String) cbxGeneroCrearCantante.getSelectedItem();
            String numSencillos = txtNumSencillosCantante.getText();
            int sencillos = Integer.parseInt(numSencillos);
            String numConciertos = txtNumConciertosCantante.getText();
            int conciertos = Integer.parseInt(numConciertos);
            String numGiras = txtNumGirasCantante.getText();
            int giras = Integer.parseInt(numGiras);
            String salario = txtSalarioCantante.getText();
            double salarioCan = Double.parseDouble(salario);

            Cantante cantante = new Cantante();
            cantante.setCodigo(codiguito);
            cantante.setNombre(nombre);
            cantante.setApellido(apellido);
            cantante.setEdad(edadcita);
            cantante.setNacionalidad(nacionalidad);
            cantante.setNombreArtistico(nombreArtistico);
            cantante.setGeneroMusical(generoMusical);
            cantante.setNumeroDeSencillos(sencillos);
            cantante.setNumeroDeConciertos(conciertos);
            cantante.setNumeroDeGiras(giras);
            cantante.setSalario(salarioCan);
            cantante.setSalarioFinal(cantante.calcularSalario(salarioCan));
            cantante.setDiscografia(new ArrayList());
            
            
            controladorCantante.registrarCantante(cantante);
            JOptionPane.showMessageDialog(this, "El/La cantante ha sido creado exitosamente !:)");

            this.limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(this, "Porfavor ingrese los datos: ");
        }
    }//GEN-LAST:event_btnAceptarCantanteActionPerformed
    private void limpiarCampos() {
        this.txtCodigoCantante.setText("");
        this.txtNombreCantante.setText("");
        this.txtApellidoCantante.setText("");
        this.txtEdadCantante.setText("");
        this.cbxPaisCrearCantante.setSelectedItem("--Selecciona un País--");
        this.cbxGeneroCrearCantante.setSelectedItem("--Selecciona un genero--");
        this.txtNomArtisticoCantante.setText("");
        this.txtNumSencillosCantante.setText("");
        this.txtNumConciertosCantante.setText("");
        this.txtNumGirasCantante.setText("");
        this.txtSalarioCantante.setText("");

    }

    public void cambiarEstadoCampos(boolean estado) {
        txtNombreCantante.setEditable(estado);
        txtApellidoCantante.setEditable(estado);
        txtEdadCantante.setEditable(estado);
        cbxPaisCrearCantante.setEditable(estado);
        txtNomArtisticoCantante.setEditable(estado);
        cbxGeneroCrearCantante.setEditable(estado);
        txtNumSencillosCantante.setEditable(estado);
        txtNumConciertosCantante.setEditable(estado);
        txtNumGirasCantante.setEditable(estado);
        txtSalarioCantante.setEditable(estado);

    }

    public List<String> generarPaises() {
        List<String> paises = new ArrayList<>();
        paises.add("Afganistán");
        paises.add("Alemania");
        paises.add("Arabia Saudita");
        paises.add("Argentina");
        paises.add("Australia");
        paises.add("Brasil");
        paises.add("Canadá");
        paises.add("China");
        paises.add("Colombia");
        paises.add("Corea del Sur");
        paises.add("Cuba");
        paises.add("Egipto");
        paises.add("España");
        paises.add("Estados Unidos");
        paises.add("Francia");
        paises.add("India");
        paises.add("Indonesia");
        paises.add("Italia");
        paises.add("Japón");
        paises.add("México");
        paises.add("Nigeria");
        paises.add("Pakistán");
        paises.add("Perú");
        paises.add("Reino Unido");
        paises.add("Rusia");
        paises.add("Sudáfrica");
        paises.add("Turquía");
        paises.add("Venezuela");
        return paises;
    }

    public List<String> generarGeneros() {
        List<String> generosMusicales = new ArrayList<>();
        generosMusicales.add("Pop");
        generosMusicales.add("Rock");
        generosMusicales.add("Hip Hop");
        generosMusicales.add("Electrónica");
        generosMusicales.add("R&B");
        generosMusicales.add("Reggae");
        generosMusicales.add("Country");
        generosMusicales.add("Jazz");
        generosMusicales.add("Clásica");
        generosMusicales.add("Metal");
        return generosMusicales;
    }

    private void cargarDatosPaises() {
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel) this.cbxPaisCrearCantante.getModel();
        List<String> paises = generarPaises();
        modelo.removeAllElements();
        for (String pais : paises) {
            modelo.addElement(pais);
        }
    }
    
    private void cargarDatosGeneros(){
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel) this.cbxGeneroCrearCantante.getModel();
        List<String> generosMusicales = generarGeneros();
        modelo.removeAllElements();
        for (String genero : generosMusicales) {
            modelo.addElement(genero);
        }
    }

    private boolean camposObligatoriosConDatos() {
        if (!this.txtCodigoCantante.getText().isEmpty() && !this.txtNombreCantante.getText().isEmpty() && !this.txtApellidoCantante.getText().isEmpty() && !this.txtEdadCantante.getText().isEmpty() && !this.cbxPaisCrearCantante.getSelectedItem().equals("--Seleccione un País--") && !this.txtNomArtisticoCantante.getText().isEmpty() && !this.cbxGeneroCrearCantante.getSelectedItem().equals("--Seleccione un género--") && !this.txtNumSencillosCantante.getText().isEmpty() && !this.txtNumConciertosCantante.getText().isEmpty() && !this.txtNumGirasCantante.getText().isEmpty() && !this.txtSalarioCantante.getText().isEmpty()) {
            return true;
        } else {
            return false;
        }
    }
    private void btnCancelarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCantanteActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarCantanteActionPerformed

    private void txtCodigoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCantanteActionPerformed

    private void txtNombreCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCantanteActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtNomArtisticoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomArtisticoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomArtisticoCantanteActionPerformed

    private void txtApellidoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCantanteActionPerformed

    private void txtEdadCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadCantanteActionPerformed

    private void txtNumSencillosCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumSencillosCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumSencillosCantanteActionPerformed

    private void txtNumConciertosCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumConciertosCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumConciertosCantanteActionPerformed

    private void txtNumGirasCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumGirasCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumGirasCantanteActionPerformed

    private void txtSalarioCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioCantanteActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cargarDatosPaises();
        cargarDatosGeneros();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarCantante;
    private javax.swing.JButton btnCancelarCantante;
    private javax.swing.JComboBox<String> cbxGeneroCrearCantante;
    private javax.swing.JComboBox<String> cbxPaisCrearCantante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellidoCreacCantante;
    private javax.swing.JLabel lblCantante;
    private javax.swing.JLabel lblCodigoCrearPersona;
    private javax.swing.JLabel lblEdadCrearCantante;
    private javax.swing.JLabel lblGeneroMuscCrearCantante;
    private javax.swing.JLabel lblNacionalidadCrearCantante;
    private javax.swing.JLabel lblNombreArtCrearCantante;
    private javax.swing.JLabel lblNombreCrearPersona1;
    private javax.swing.JLabel lblNumConcCrearCantante;
    private javax.swing.JLabel lblNumGirasCrearCantante;
    private javax.swing.JLabel lblNumSencillosCrearCantante;
    private javax.swing.JLabel lblSalarioBaseCrearCantante;
    private javax.swing.JLabel lblcantantaFondo;
    private javax.swing.JLabel lblicono;
    private javax.swing.JPanel panelCantante;
    private javax.swing.JTextField txtApellidoCantante;
    private javax.swing.JTextField txtCodigoCantante;
    private javax.swing.JTextField txtEdadCantante;
    private javax.swing.JTextField txtNomArtisticoCantante;
    private javax.swing.JTextField txtNombreCantante;
    private javax.swing.JTextField txtNumConciertosCantante;
    private javax.swing.JTextField txtNumGirasCantante;
    private javax.swing.JTextField txtNumSencillosCantante;
    private javax.swing.JTextField txtSalarioCantante;
    // End of variables declaration//GEN-END:variables
}
