/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica_05_ssuquilanda_jabad.vista.cantante;

import ec.edu.ups.practica_05_ssuquilanda_jabad.controlador.ControladorCantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Cantante;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaBuscarCantantePorDisco extends javax.swing.JInternalFrame {

    private ControladorCantante controladorCantante;
    private ResourceBundle mensajes;
    /**
     * Creates new form VentanaBuscarCantantePorDisco
     */
    public VentanaBuscarCantantePorDisco(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
    }
     public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jLabel1.setText(mensajes.getString("txtBuscarCantantePorCódigoDeDisco"));
        lblCodigoDiscoBuscarCantante.setText(mensajes.getString("txtCódigoDisco"));
        lblCodigoCantante.setText(mensajes.getString("txtCódigoCantante"));
        lblNombreBuscarCantantePorDisco.setText(mensajes.getString("txtNombre"));        
        lblApellidoBuscarCantante.setText(mensajes.getString("txtApellido"));        
        lblEdadBuscarCantante.setText(mensajes.getString("txtEdad"));        
        lblNacionalidadBuscarCantante.setText(mensajes.getString("txtNacionalidad"));   
        cbxPaisesActualizarCantante.setSelectedItem(mensajes.getString("txtSeleccionarPaís"));
        cbxGeneroMusicalCantante.setSelectedItem(mensajes.getString("txtSeleccionarGénero"));
        lblNombreArtisticoBuscarCantante.setText(mensajes.getString("txtNombreArtístico"));        
        lblGeneroBuscarCantante.setText(mensajes.getString("txtGéneroMusical"));        
        lblNumSencillosBuscarCantante.setText(mensajes.getString("txtNúmeroDeSencillos"));        
        lblNimConciertosBuscarCantante.setText(mensajes.getString("txtNúmeroDeConciertos"));        
        lblNumGirasBuscarCantante.setText(mensajes.getString("txtNúmeroDeGiras"));        
        lblSalarioBuscarCantante.setText(mensajes.getString("txtSalarioBase"));
        lblSalarioFinalBuscarCantante.setText(mensajes.getString("txtSalarioFinal"));
        btnBuscarPorDiscoCantante.setText(mensajes.getString("txtBuscar"));
        btnCancelarBuscarCantantePorDisco.setText(mensajes.getString("txtCancelar"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcantantaFondo = new javax.swing.JLabel();
        lblicono = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblApellidoBuscarCantante = new javax.swing.JLabel();
        lblNumGirasBuscarCantante = new javax.swing.JLabel();
        txtCodigoDisco = new javax.swing.JTextField();
        txtNombreCantante = new javax.swing.JTextField();
        btnBuscarPorDiscoCantante = new javax.swing.JButton();
        btnCancelarBuscarCantantePorDisco = new javax.swing.JButton();
        lblCantante = new javax.swing.JLabel();
        lblNombreBuscarCantantePorDisco = new javax.swing.JLabel();
        lblCodigoDiscoBuscarCantante = new javax.swing.JLabel();
        lblEdadBuscarCantante = new javax.swing.JLabel();
        lblNacionalidadBuscarCantante = new javax.swing.JLabel();
        lblNombreArtisticoBuscarCantante = new javax.swing.JLabel();
        lblGeneroBuscarCantante = new javax.swing.JLabel();
        lblNumSencillosBuscarCantante = new javax.swing.JLabel();
        lblNimConciertosBuscarCantante = new javax.swing.JLabel();
        txtNomArtisticoCantante = new javax.swing.JTextField();
        txtApellidoCantante = new javax.swing.JTextField();
        txtEdadCantante = new javax.swing.JTextField();
        txtNumSencillosCantante = new javax.swing.JTextField();
        txtNumConciertosCantante = new javax.swing.JTextField();
        txtNumGirasCantante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblSalarioBuscarCantante = new javax.swing.JLabel();
        txtSalarioFinalCantante = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        lblCodigoCantante = new javax.swing.JLabel();
        txtCodigoCantante = new javax.swing.JTextField();
        lblSalarioFinalBuscarCantante = new javax.swing.JLabel();
        txtSalarioCantante1 = new javax.swing.JTextField();
        cbxPaisesActualizarCantante = new javax.swing.JComboBox<>();
        cbxGeneroMusicalCantante = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Buscar Cantante Por Codigo de Disco"));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcantantaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/silue h.png"))); // NOI18N
        getContentPane().add(lblcantantaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 290, 540));

        lblicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpeg"))); // NOI18N
        getContentPane().add(lblicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 360, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblApellidoBuscarCantante.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblApellidoBuscarCantante.setText("Apellido:");
        jPanel2.add(lblApellidoBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 210, 30));

        lblNumGirasBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumGirasBuscarCantante.setText("Num. Giras:");
        jPanel2.add(lblNumGirasBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 180, 30));

        txtCodigoDisco.setToolTipText("Ingrese el codigo del cantante");
        txtCodigoDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDiscoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodigoDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 220, 30));

        txtNombreCantante.setToolTipText("Ingrese el nombre del cantante");
        txtNombreCantante.setEnabled(false);
        txtNombreCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 220, 30));

        btnBuscarPorDiscoCantante.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBuscarPorDiscoCantante.setText("Buscar");
        btnBuscarPorDiscoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorDiscoCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarPorDiscoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 106, 32));

        btnCancelarBuscarCantantePorDisco.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelarBuscarCantantePorDisco.setText("Cancelar");
        btnCancelarBuscarCantantePorDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBuscarCantantePorDiscoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelarBuscarCantantePorDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, 104, 32));

        lblCantante.setFont(new java.awt.Font("AkayaTelivigala", 1, 36)); // NOI18N
        lblCantante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/My project-1-3.png"))); // NOI18N
        lblCantante.setText("UPS Musik");
        lblCantante.setPreferredSize(new java.awt.Dimension(200, 400));
        jPanel2.add(lblCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 330, 50));

        lblNombreBuscarCantantePorDisco.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblNombreBuscarCantantePorDisco.setText("Nombre:");
        jPanel2.add(lblNombreBuscarCantantePorDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 30));

        lblCodigoDiscoBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblCodigoDiscoBuscarCantante.setText("Codigo Disco:");
        jPanel2.add(lblCodigoDiscoBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 170, 30));

        lblEdadBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblEdadBuscarCantante.setText("Edad:");
        jPanel2.add(lblEdadBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 78, 30));

        lblNacionalidadBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNacionalidadBuscarCantante.setText("Nacionalidad:");
        jPanel2.add(lblNacionalidadBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 280, 30));

        lblNombreArtisticoBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreArtisticoBuscarCantante.setText("Nombre Artistico:");
        jPanel2.add(lblNombreArtisticoBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 380, 30));

        lblGeneroBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblGeneroBuscarCantante.setText("Genero Musical:");
        jPanel2.add(lblGeneroBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 370, 30));

        lblNumSencillosBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNumSencillosBuscarCantante.setText("Num. Sencillos:");
        jPanel2.add(lblNumSencillosBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 340, 30));

        lblNimConciertosBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNimConciertosBuscarCantante.setText("Num. Conciertos:");
        jPanel2.add(lblNimConciertosBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 310, 30));

        txtNomArtisticoCantante.setToolTipText("Ingrese el nombre artistico del cantante");
        txtNomArtisticoCantante.setEnabled(false);
        txtNomArtisticoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomArtisticoCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtNomArtisticoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 220, 30));

        txtApellidoCantante.setToolTipText("Ingrese el apellido del cantante");
        txtApellidoCantante.setEnabled(false);
        txtApellidoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtApellidoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 220, 30));

        txtEdadCantante.setToolTipText("Ingrese le edad del cantante");
        txtEdadCantante.setEnabled(false);
        txtEdadCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtEdadCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 220, 30));

        txtNumSencillosCantante.setToolTipText("Ingrese el numero de sencillos del cantante");
        txtNumSencillosCantante.setEnabled(false);
        txtNumSencillosCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumSencillosCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumSencillosCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 220, 30));

        txtNumConciertosCantante.setToolTipText("Ingrese el numero de conciertos dados por el cantante");
        txtNumConciertosCantante.setEnabled(false);
        txtNumConciertosCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumConciertosCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumConciertosCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 220, 30));

        txtNumGirasCantante.setToolTipText("Ingrese el numero de giras del cantante");
        txtNumGirasCantante.setEnabled(false);
        txtNumGirasCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumGirasCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumGirasCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 220, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Buscar cantante por el codigo de un disco:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 300, 30));

        lblSalarioBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblSalarioBuscarCantante.setText("Salario:");
        jPanel2.add(lblSalarioBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 260, 30));

        txtSalarioFinalCantante.setToolTipText("Ingrese el nombre de la nueva persona");
        txtSalarioFinalCantante.setEnabled(false);
        txtSalarioFinalCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioFinalCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtSalarioFinalCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 220, 30));

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblCodigoCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblCodigoCantante.setText("Codigo Cantante:");
        jPanel2.add(lblCodigoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 320, 30));

        txtCodigoCantante.setToolTipText("Ingrese el codigo del cantante");
        txtCodigoCantante.setEnabled(false);
        txtCodigoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodigoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 220, 30));

        lblSalarioFinalBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblSalarioFinalBuscarCantante.setText("Salario Final:");
        jPanel2.add(lblSalarioFinalBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 220, 30));

        txtSalarioCantante1.setToolTipText("Ingrese el nombre de la nueva persona");
        txtSalarioCantante1.setEnabled(false);
        txtSalarioCantante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioCantante1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtSalarioCantante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 220, 30));

        cbxPaisesActualizarCantante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona un País--" }));
        cbxPaisesActualizarCantante.setToolTipText("Puede cambiar la nacionalidad");
        cbxPaisesActualizarCantante.setEnabled(false);
        cbxPaisesActualizarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisesActualizarCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(cbxPaisesActualizarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 220, 30));

        cbxGeneroMusicalCantante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona un Género--" }));
        cbxGeneroMusicalCantante.setToolTipText("Puede cambiar el género musical");
        cbxGeneroMusicalCantante.setEnabled(false);
        cbxGeneroMusicalCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeneroMusicalCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(cbxGeneroMusicalCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 220, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDiscoActionPerformed

    private void txtNombreCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCantanteActionPerformed

    private void btnBuscarPorDiscoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorDiscoCantanteActionPerformed
        String codigo = txtCodigoDisco.getText();
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El codigo del disco del cantante a buscar no ha sido ingresado!");
        } else {
            int codiguito = Integer.parseInt(codigo);
            Cantante cantante = controladorCantante.verCantantexDisco(codiguito);
            if (cantante != null) {
                String codigoCan = String.valueOf(cantante.getCodigo());
                txtCodigoCantante.setText(codigoCan);
                txtNombreCantante.setText(cantante.getNombre());
                txtApellidoCantante.setText(cantante.getApellido());
                String edad = String.valueOf(cantante.getEdad());
                txtEdadCantante.setText(edad);
                cbxPaisesActualizarCantante.setSelectedItem(cantante.getNacionalidad());
                txtNomArtisticoCantante.setText(cantante.getNombreArtistico());
                cbxGeneroMusicalCantante.setSelectedItem(cantante.getGeneroMusical());
                String numSencillos = String.valueOf(cantante.getNumeroDeSencillos());
                txtNumSencillosCantante.setText(numSencillos);
                String numConciertos = String.valueOf(cantante.getNumeroDeConciertos());
                txtNumConciertosCantante.setText(numConciertos);
                String numGiras = String.valueOf(cantante.getNumeroDeGiras());
                txtNumGirasCantante.setText(numGiras);
                String salarioCan = String.valueOf(cantante.getSalario());
                String salarioCanF = String.valueOf(cantante.getSalarioFinal());
                txtSalarioFinalCantante.setText(salarioCanF);
                txtSalarioCantante1.setText(salarioCan);
                JOptionPane.showMessageDialog(this, "El/La cantante con disco de codigo " + codiguito + "ha sido encontrado  exitosamente1:)");

            } else {
                JOptionPane.showMessageDialog(this, "El/La cantante con disco de codigo " + codiguito + " no ha sido encontrada !:(");

                this.limpiarCampos();
            }
        }
    }//GEN-LAST:event_btnBuscarPorDiscoCantanteActionPerformed

    private void btnCancelarBuscarCantantePorDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBuscarCantantePorDiscoActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarBuscarCantantePorDiscoActionPerformed

    private void txtNomArtisticoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomArtisticoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomArtisticoCantanteActionPerformed

    private void txtApellidoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCantanteActionPerformed

    private void txtEdadCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadCantanteActionPerformed

    private void txtNumSencillosCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumSencillosCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumSencillosCantanteActionPerformed

    private void txtNumConciertosCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumConciertosCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumConciertosCantanteActionPerformed

    private void txtNumGirasCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumGirasCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumGirasCantanteActionPerformed

    private void txtSalarioFinalCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioFinalCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioFinalCantanteActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtCodigoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCantanteActionPerformed

    private void txtSalarioCantante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioCantante1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioCantante1ActionPerformed

    private void cbxPaisesActualizarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisesActualizarCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPaisesActualizarCantanteActionPerformed

    private void cbxGeneroMusicalCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeneroMusicalCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGeneroMusicalCantanteActionPerformed
    private void limpiarCampos() {
        this.txtCodigoCantante.setText("");
        this.txtNombreCantante.setText("");
        this.txtApellidoCantante.setText("");
        this.txtEdadCantante.setText("");
        this.cbxPaisesActualizarCantante.setSelectedItem("--Selecciona un País--");
        this.cbxGeneroMusicalCantante.setSelectedItem("--Selecciona un Género--");
        this.txtNomArtisticoCantante.setText("");
        this.txtNumSencillosCantante.setText("");
        this.txtNumConciertosCantante.setText("");
        this.txtNumGirasCantante.setText("");
        this.txtSalarioFinalCantante.setText("");

    }
    public List<String> generarPaises() {
        List<String> paises = new ArrayList<>();
        paises.add("Afganistán");
        paises.add("Alemania");
        paises.add("Arabia Saudita");
        paises.add("Argentina");
        paises.add("Australia");
        paises.add("Brasil");
        paises.add("Canadá");
        paises.add("China");
        paises.add("Colombia");
        paises.add("Corea del Sur");
        paises.add("Cuba");
        paises.add("Egipto");
        paises.add("España");
        paises.add("Estados Unidos");
        paises.add("Francia");
        paises.add("India");
        paises.add("Indonesia");
        paises.add("Italia");
        paises.add("Japón");
        paises.add("México");
        paises.add("Nigeria");
        paises.add("Pakistán");
        paises.add("Perú");
        paises.add("Reino Unido");
        paises.add("Rusia");
        paises.add("Sudáfrica");
        paises.add("Turquía");
        paises.add("Venezuela");
        return paises;
    }

    private void cargarDatosPaises() {
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel) this.cbxPaisesActualizarCantante.getModel();
        List<String> paises = generarPaises();
        modelo.removeAllElements();
        for (String pais : paises) {
            modelo.addElement(pais);
        }
    }
    
    public List<String> generarGeneros() {
        List<String> generosMusicales = new ArrayList<>();
        generosMusicales.add("Pop");
        generosMusicales.add("Rock");
        generosMusicales.add("Hip Hop");
        generosMusicales.add("Electrónica");
        generosMusicales.add("R&B");
        generosMusicales.add("Reggae");
        generosMusicales.add("Country");
        generosMusicales.add("Jazz");
        generosMusicales.add("Clásica");
        generosMusicales.add("Metal");
        return generosMusicales;
    }
    private void cargarDatosGeneros(){
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel) this.cbxGeneroMusicalCantante.getModel();
        List<String> generosMusicales = generarGeneros();
        modelo.removeAllElements();
        for (String genero : generosMusicales) {
            modelo.addElement(genero);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPorDiscoCantante;
    private javax.swing.JButton btnCancelarBuscarCantantePorDisco;
    private javax.swing.JComboBox<String> cbxGeneroMusicalCantante;
    private javax.swing.JComboBox<String> cbxPaisesActualizarCantante;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblApellidoBuscarCantante;
    private javax.swing.JLabel lblCantante;
    private javax.swing.JLabel lblCodigoCantante;
    private javax.swing.JLabel lblCodigoDiscoBuscarCantante;
    private javax.swing.JLabel lblEdadBuscarCantante;
    private javax.swing.JLabel lblGeneroBuscarCantante;
    private javax.swing.JLabel lblNacionalidadBuscarCantante;
    private javax.swing.JLabel lblNimConciertosBuscarCantante;
    private javax.swing.JLabel lblNombreArtisticoBuscarCantante;
    private javax.swing.JLabel lblNombreBuscarCantantePorDisco;
    private javax.swing.JLabel lblNumGirasBuscarCantante;
    private javax.swing.JLabel lblNumSencillosBuscarCantante;
    private javax.swing.JLabel lblSalarioBuscarCantante;
    private javax.swing.JLabel lblSalarioFinalBuscarCantante;
    private javax.swing.JLabel lblcantantaFondo;
    private javax.swing.JLabel lblicono;
    private javax.swing.JTextField txtApellidoCantante;
    private javax.swing.JTextField txtCodigoCantante;
    private javax.swing.JTextField txtCodigoDisco;
    private javax.swing.JTextField txtEdadCantante;
    private javax.swing.JTextField txtNomArtisticoCantante;
    private javax.swing.JTextField txtNombreCantante;
    private javax.swing.JTextField txtNumConciertosCantante;
    private javax.swing.JTextField txtNumGirasCantante;
    private javax.swing.JTextField txtNumSencillosCantante;
    private javax.swing.JTextField txtSalarioCantante1;
    private javax.swing.JTextField txtSalarioFinalCantante;
    // End of variables declaration//GEN-END:variables
}
