/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica_05_ssuquilanda_jabad.vista.compositor;

import ec.edu.ups.practica_05_ssuquilanda_jabad.controlador.ControladorCompositor;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Cancion;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Cantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Compositor;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaListarCompositor extends javax.swing.JInternalFrame {

    private ControladorCompositor controladorCompositor;
    private ResourceBundle mensajes;
    /**
     * Creates new form VentanaListarCompositor
     */
    public VentanaListarCompositor(ControladorCompositor controladorCompositor) {
        initComponents();
        this.controladorCompositor = controladorCompositor;

    }
    public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jLabel3.setText(mensajes.getString("txtListaDeCompositores"));
        tblListarCanciones1.setText(mensajes.getString("txtListaDeCanciones"));
        jLabel5.setText(mensajes.getString("txtIngresarCódigoDelCantanteParaMostrarListaDeÁlbumesYClientes"));        
        tblListarCanciones.setText(mensajes.getString("txtListaDeClientes"));        
        btnBuscarCompositor.setText(mensajes.getString("txtBuscar"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblCantante = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarCompositor = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListarCancion = new javax.swing.JTable();
        tblListarCanciones = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tblListarCanciones1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblListarClientes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoBuscarCompositor = new javax.swing.JTextField();
        btnBuscarCompositor = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCantante.setFont(new java.awt.Font("AkayaTelivigala", 1, 36)); // NOI18N
        lblCantante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/My project-1-3.png"))); // NOI18N
        lblCantante.setText("UPS Musik");
        lblCantante.setPreferredSize(new java.awt.Dimension(200, 400));
        jPanel2.add(lblCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 270, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/silue h.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -10, 180, 270));

        tblListarCompositor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Edad", "Nacionalidad", "Numero Composiciones", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListarCompositor);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 1350, -1));

        tblListarCancion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Titulo", "Letra", "Tiempo en Minutos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblListarCancion);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, 630, 350));

        tblListarCanciones.setFont(new java.awt.Font("AkayaKanadaka", 1, 24)); // NOI18N
        tblListarCanciones.setText("Lista de Clientes:");
        jPanel2.add(tblListarCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1020, 240, 50));

        jLabel3.setFont(new java.awt.Font("AkayaKanadaka", 1, 24)); // NOI18N
        jLabel3.setText("Lista de Compositores:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 380, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disco.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 500, 470));

        tblListarCanciones1.setFont(new java.awt.Font("AkayaKanadaka", 1, 24)); // NOI18N
        tblListarCanciones1.setText("Lista de Canciones:");
        jPanel2.add(tblListarCanciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 240, 50));

        tblListarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Edad", "Nacionalidad", "Nombre Artistico", "Genero Musical", "Numero Sencillos", "Numero Conciertos", "Numero Giras", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblListarClientes);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1070, 1350, -1));

        jLabel5.setFont(new java.awt.Font("Al Bayan", 1, 14)); // NOI18N
        jLabel5.setText("Ingrese el codigo del cantante del cual se va a mostrar la lista de discos y clientes:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, -1, -1));

        txtCodigoBuscarCompositor.setToolTipText("Ingrese el codigo del compositor a buscar");
        txtCodigoBuscarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBuscarCompositorActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodigoBuscarCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 310, -1));

        btnBuscarCompositor.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBuscarCompositor.setText("Buscar");
        btnBuscarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCompositorActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCompositor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        this.cargarDatosTablaCompositor();
        this.cargarDatosTablaCancion();

    }//GEN-LAST:event_formInternalFrameActivated

    private void txtCodigoBuscarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBuscarCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBuscarCompositorActionPerformed

    private void btnBuscarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCompositorActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoBuscarCompositor.getText();
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El codigo del  compositor a buscar no ha sido ingresado!");
        } else {
            int codiguito = Integer.parseInt(codigo);
            Compositor compositor = controladorCompositor.buscarCompositor(codiguito);
            if (compositor != null) {
                this.cargarDatosTablaCompositor();
                this.cargarDatosTablaCancion();
                this.cargarDatosTablaCliente();
                this.cargarDatosTablaCompositor();
            }
        }
    }//GEN-LAST:event_btnBuscarCompositorActionPerformed
    private void cargarDatosTablaCompositor() {
        DefaultTableModel modeloCompositor = (DefaultTableModel) this.tblListarCompositor.getModel();
        modeloCompositor.setNumRows(0);
        List<Compositor> listaCompositores = controladorCompositor.listarCompositores();
        for (Compositor compositor : listaCompositores) {

            String codigo = String.valueOf(compositor.getCodigo());
            String nombre = compositor.getNombre();
            String apellido = compositor.getApellido();
            String edad = String.valueOf(compositor.getEdad());
            String nacionalidad = compositor.getNacionalidad();
            String numComposiciones = String.valueOf(compositor.getNumeroDeComposiciones());
            String salario = String.valueOf(compositor.getSalario());

            Object[] rowData = {codigo, nombre, apellido, edad, nacionalidad, numComposiciones, salario};
            modeloCompositor.addRow(rowData);
        }
        this.tblListarClientes.setModel(modeloCompositor);
    }

    private void cargarDatosTablaCancion() {
        DefaultTableModel modelo = (DefaultTableModel) this.tblListarCancion.getModel();
        modelo.setNumRows(0);
        String codigoCompositor = txtCodigoBuscarCompositor.getText();
        int codiguito = Integer.parseInt(codigoCompositor);
        Compositor compositorSeleccionado = controladorCompositor.buscarCompositor(codiguito);
        List<Cancion> cancionesTop100Billboard = controladorCompositor.listarCanciones(compositorSeleccionado);
        for (Cancion cancion : cancionesTop100Billboard) {

            String codigo = String.valueOf(cancion.getCodigo());
            String titulo = cancion.getTitulo();
            String letra = cancion.getLetra();
            String tiempo = String.valueOf(cancion.getTiempoEnMinutos());

            Object[] rowData = {codigo, titulo, letra, tiempo};
            modelo.addRow(rowData);
        }
        this.tblListarCancion.setModel(modelo);
    }

    private void cargarDatosTablaCliente() {
        DefaultTableModel modeloCantante = (DefaultTableModel) this.tblListarClientes.getModel();
        modeloCantante.setNumRows(0);
        String codigoCompositor = txtCodigoBuscarCompositor.getText();
        int codiguito = Integer.parseInt(codigoCompositor);
        Compositor compositorSeleccionado = controladorCompositor.buscarCompositor(codiguito);
        List<Cantante> listaCantantes = controladorCompositor.listarClientes(compositorSeleccionado);
        for (Cantante cantante : listaCantantes) {

            String codigo = String.valueOf(cantante.getCodigo());
            String nombre = cantante.getNombre();
            String apellido = cantante.getApellido();
            String edad = String.valueOf(cantante.getEdad());
            String nacionalidad = cantante.getNacionalidad();
            String nomArtistico = cantante.getNombreArtistico();
            String genMusical = cantante.getGeneroMusical();
            String numSencillos = String.valueOf(cantante.getNumeroDeSencillos());
            String numConciertos = String.valueOf(cantante.getNumeroDeConciertos());
            String numGiras = String.valueOf(cantante.getNumeroDeGiras());
            String salario = String.valueOf(cantante.getSalario());

            Object[] rowData = {codigo, nombre, apellido, edad, nacionalidad, nomArtistico, genMusical, numSencillos, numConciertos, numGiras, salario};
            modeloCantante.addRow(rowData);
        }
        this.tblListarClientes.setModel(modeloCantante);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCompositor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCantante;
    private javax.swing.JTable tblListarCancion;
    private javax.swing.JLabel tblListarCanciones;
    private javax.swing.JLabel tblListarCanciones1;
    private javax.swing.JTable tblListarClientes;
    private javax.swing.JTable tblListarCompositor;
    private javax.swing.JTextField txtCodigoBuscarCompositor;
    // End of variables declaration//GEN-END:variables
}
